const fs=require('node:fs');
const read=p=>fs.existsSync(p)?fs.readFileSync(p,'utf8'):'';
const write=(p,s)=>fs.writeFileSync(p,s);

let h=read('public/admin-mobile.html');
if(h){
 h=h.replace('window.SAINTSAI_ADMIN_UI_VERSION="v5"','window.SAINTSAI_ADMIN_UI_VERSION="v6"').replaceAll('js/config.js?v=5','js/config.js?v=6').replaceAll('js/auth.js?v=5','js/auth.js?v=6').replaceAll('js/api.js?v=5','js/api.js?v=6');
 h=h.replace(/<header class="top">[\s\S]*?<\/header>/,'<header class="saintsHeader"><div class="saintsBrand"><div class="saintsWord">SaintsAI</div><div class="saintsBy">By Alves</div></div><button id="menuBtn" class="menuBtn saintsMenu" type="button" aria-label="Abrir menu">☰</button></header><div class="pageLead"><h1 id="pageTitle">Início</h1><p id="pageSub">Resumo do seu negócio</p></div>');
 h=h.replace('<div class="brand"><div class="bot">🤖</div><div><h2>Agente SaintsAI</h2><p>Inteligência que vende</p></div></div>','<div class="brand saintsDrawerBrand"><div><div class="saintsWord">SaintsAI</div><div class="saintsBy">By Alves</div></div></div>');
 const css='<style id="saints-v6-theme">'+
 '.saintsHeader{position:sticky;top:0;z-index:50;display:flex;align-items:center;justify-content:space-between;margin:-12px -12px 14px;padding:calc(12px + env(safe-area-inset-top)) 14px 12px;background:linear-gradient(180deg,rgba(9,8,18,.98),rgba(9,8,18,.9));backdrop-filter:blur(18px);border-bottom:1px solid var(--line);box-shadow:0 8px 26px rgba(0,0,0,.14)}'+
 '.saintsBrand{display:flex;flex-direction:column;line-height:1}.saintsWord{font-family:Georgia,Times New Roman,serif;font-size:29px;font-style:italic;font-weight:800;letter-spacing:-1.2px;background:linear-gradient(110deg,#fff 5%,#c4b5fd 48%,#8b5cf6 92%);-webkit-background-clip:text;background-clip:text;color:transparent}.saintsBy{margin-top:5px;padding-left:2px;font-family:Trebuchet MS,Arial,sans-serif;font-size:10px;font-weight:800;letter-spacing:3px;text-transform:uppercase;color:#a78bfa}.saintsMenu{flex:0 0 46px;margin-left:auto;display:grid;place-items:center}.pageLead{margin:2px 2px 15px}.pageLead h1{margin:0;font-size:22px}.pageLead p{margin:4px 0 0;color:var(--muted);font-size:13px}.saintsDrawerBrand{padding:4px 2px 10px}.saintsDrawerBrand .saintsWord{font-size:32px}'+
 'html[data-saints-theme="light"],html[data-saints-theme="light"] body{--bg:#f4f9ff;--card:#fff;--line:rgba(22,119,255,.18);--purple:#1677ff;--text:#10213a;--muted:#63758e;background:radial-gradient(circle at 90% 0,rgba(100,181,255,.34) 0,rgba(223,241,255,.55) 28%,#f8fbff 64%,#eef7ff 100%)!important;color:#10213a!important}'+
 'html[data-saints-theme="light"] .saintsHeader{background:linear-gradient(180deg,rgba(255,255,255,.98),rgba(238,247,255,.94));border-bottom-color:rgba(22,119,255,.18)}html[data-saints-theme="light"] .saintsWord{background:linear-gradient(110deg,#0b4fb3 5%,#1677ff 48%,#64b5ff 96%);-webkit-background-clip:text;background-clip:text;color:transparent}html[data-saints-theme="light"] .saintsBy{color:#3578c8}'+
 'html[data-saints-theme="light"] .card,html[data-saints-theme="light"] .metric{background:linear-gradient(145deg,#fff,#eff7ff)!important;border-color:rgba(22,119,255,.16)!important;box-shadow:0 10px 30px rgba(37,112,190,.08)}html[data-saints-theme="light"] .field input,html[data-saints-theme="light"] .field textarea,html[data-saints-theme="light"] .field select,html[data-saints-theme="light"] select{background:#fff!important;color:#10213a!important;border-color:rgba(22,119,255,.20)!important}'+
 'html[data-saints-theme="light"] .primary,html[data-saints-theme="light"] .chip.active,html[data-saints-theme="light"] .plan.active,html[data-saints-theme="light"] .nav button.active{background:linear-gradient(135deg,#0f6fe8,#38a0ff)!important;color:#fff!important;border-color:transparent!important}html[data-saints-theme="light"] .secondary{background:#eaf4ff!important;color:#165cae!important;border-color:rgba(22,119,255,.18)!important}html[data-saints-theme="light"] .drawer{background:linear-gradient(180deg,#fff,#eaf5ff)!important;border-right-color:rgba(22,119,255,.17)!important}html[data-saints-theme="light"] .nav button{color:#17304f!important;background:rgba(22,119,255,.045)!important}html[data-saints-theme="light"] .nav button.active{color:#fff!important}'+
 'html[data-saints-theme="light"] .menuBtn,html[data-saints-theme="light"] .chip,html[data-saints-theme="light"] .plan,html[data-saints-theme="light"] .pick,html[data-saints-theme="light"] .navSub button{background:linear-gradient(180deg,#fff,#f1f7ff)!important;color:#17304f!important;border-color:rgba(22,119,255,.18)!important}html[data-saints-theme="light"] .saleRow{background:#f5faff!important;border-color:rgba(22,119,255,.12)!important}</style>';
 h=h.replace('</head>',css+'</head>');
 const js='<script id="saints-v6-theme-js">(function(){function r(){var s=localStorage.getItem("saintsai_admin_theme")||"dark";if(s==="system")s=matchMedia("(prefers-color-scheme: light)").matches?"light":"dark";return s==="light"?"light":"dark"}function a(){document.documentElement.setAttribute("data-saints-theme",r())}a();window.addEventListener("storage",a);document.addEventListener("change",function(e){if(e.target&&e.target.id==="adminTheme")setTimeout(a,0)});window.applySaintsAdminTheme=a})();<\/script>';
 h=h.replace('</body>',js+'</body>');
 write('public/admin-mobile.html',h);
}

const redirect=hash=>'<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate"><script>location.replace("admin-mobile.html?v=6#'+hash+'")<\/script></head><body></body></html>';
write('public/admin.html',redirect('home'));
write('public/configuracoes.html',redirect('config'));

const functional=['admin-cliente.html','admin-cliente-plano.html','admin-cliente-whatsapp.html','admin-estoque.html'];
const fx='<style id="saints-v6-functional-theme">html,body{background:radial-gradient(circle at 90% 0,#1b1232 0,#090812 36%,#07070c 100%)!important}body:before{content:"SaintsAI";display:block;position:sticky;top:0;z-index:999;padding:calc(13px + env(safe-area-inset-top)) 60px 4px 16px;background:linear-gradient(180deg,rgba(9,8,18,.98),rgba(9,8,18,.9));border-bottom:1px solid rgba(157,92,255,.24);font:italic 800 27px Georgia,serif;color:#e9ddff}body:after{content:"BY ALVES";position:fixed;z-index:1000;left:18px;top:calc(43px + env(safe-area-inset-top));font:800 9px Arial,sans-serif;letter-spacing:2.5px;color:#a78bfa;pointer-events:none}html[data-saints-theme="light"],html[data-saints-theme="light"] body{background:radial-gradient(circle at 90% 0,#cfeaff 0,#f7fbff 45%,#eef7ff 100%)!important;color:#10213a!important}html[data-saints-theme="light"] body:before{background:linear-gradient(180deg,#fff,#ebf6ff);border-bottom-color:rgba(22,119,255,.18);color:#126bd8}html[data-saints-theme="light"] body:after{color:#397fc9}</style>';
const fj='<script id="saints-v6-functional-theme-js">(function(){var s=localStorage.getItem("saintsai_admin_theme")||"dark";if(s==="system")s=matchMedia("(prefers-color-scheme: light)").matches?"light":"dark";document.documentElement.setAttribute("data-saints-theme",s==="light"?"light":"dark");document.addEventListener("click",function(e){var a=e.target.closest&&e.target.closest("a");if(!a)return;var h=a.getAttribute("href")||"";if(h==="admin.html"||h==="configuracoes.html"||h==="dashboard.html"||h.indexOf("pedidos")>=0){e.preventDefault();location.href="admin-mobile.html?v=6#home"}},true)})();<\/script>';
for(const f of functional){const p='public/'+f;let x=read(p);if(!x)continue;x=x.replace(/href=["']admin\.html[^"']*["']/g,'href="admin-mobile.html?v=6#home"').replace(/href=["']configuracoes\.html[^"']*["']/g,'href="admin-mobile.html?v=6#config"');if(!x.includes('saints-v6-functional-theme'))x=x.replace('</head>',fx+'</head>');if(!x.includes('saints-v6-functional-theme-js'))x=x.replace('</body>',fj+'</body>');write(p,x)}

if(fs.existsSync('public/service-worker.js')){let sw=read('public/service-worker.js');sw=sw.replace(/saintsai-v\d+/g,'saintsai-v6');if(!sw.includes("SAINTSAI_ADMIN_CACHE_BUSTER='v6'"))sw="const SAINTSAI_ADMIN_CACHE_BUSTER='v6';\n"+sw;write('public/service-worker.js',sw)}
console.log('Admin UI v6 aplicado: legado neutralizado, header superior e tema claro azul/branco.');
// v6 redeploy marker
