const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function routeHarness({loja={id:'12345678-1234-1234-1234-123456789abc'},dbError=null,result={enviados:1,dispositivos:1}}={}){
 const code=fs.readFileSync('src/routes/admin.routes.js','utf8'),start=code.indexOf("router.post('/lojas/:lojaId/notificacao-teste'"),end=code.indexOf('\nmodule.exports',start);let handler,guard,pushCalls=[];
 const db={from(name){assert.equal(name,'lojas');return{select(){return this},eq(_,id){assert.equal(id,'12345678-1234-1234-1234-123456789abc');return this},async maybeSingle(){return{data:loja,error:dbError}}}}};const exigirAdmin=()=>{};
 vm.runInNewContext(code.slice(start,end),{router:{post(path,g,h){guard=g;handler=h}},exigirAdmin,console:{error(){}},require(p){return p.includes('clientPush')?{async notificarLoja(...args){pushCalls.push(args);return result}}:db}});
 assert.equal(guard,exigirAdmin);return {async run(body,id='12345678-1234-1234-1234-123456789abc'){const res={statusCode:200,status(n){this.statusCode=n;return this},json(v){this.body=v;return this}};await handler({body,params:{lojaId:id}},res);return res},pushCalls};
}
test('personalized notification targets only selected shop without writing sales',async()=>{const h=routeHarness();const r=await h.run({titulo:' Venda de teste ',mensagem:' Olá, loja! '});assert.equal(r.statusCode,200);assert.equal(r.body.enviados,1);assert.equal(h.pushCalls.length,1);assert.equal(h.pushCalls[0][0],'12345678-1234-1234-1234-123456789abc');assert.deepEqual(JSON.parse(JSON.stringify(h.pushCalls[0][1])),{title:'Venda de teste',body:'Olá, loja!',tipo:'teste_venda'});});
test('invalid shop or oversized/blank input never sends',async()=>{for(const [body,id] of [[{titulo:'',mensagem:'Oi'}], [{titulo:'x'.repeat(81),mensagem:'Oi'}],[{titulo:'x',mensagem:'x'.repeat(501)}],[{titulo:'x',mensagem:'oi'},'invalid']]){const h=routeHarness();assert.equal((await h.run(body,id)).statusCode,400);assert.equal(h.pushCalls.length,0);}});
test('nonexistent shop never sends',async()=>{const h=routeHarness({loja:null});assert.equal((await h.run({titulo:'Teste',mensagem:'Oi'})).statusCode,404);assert.equal(h.pushCalls.length,0);});
test('no registered devices is reported without claiming delivery',async()=>{const h=routeHarness({result:{enviados:0,dispositivos:0}});const r=await h.run({titulo:'Teste',mensagem:'Oi'});assert.equal(r.body.enviados,0);assert.equal(r.body.dispositivos,0);assert.equal(r.statusCode,409);});
test('WhatsApp frontend prefers native bridge and uses external HTTPS fallback',()=>{const p=fs.readFileSync('public/admin-prospeccao.html','utf8');assert.match(p,/AndroidAgent.openWhatsApp\(phone\)/);assert.match(p,/https:\/\/api.whatsapp.com\/send\?phone=/);assert.doesNotMatch(p,/window.location.href=a.href/);assert.doesNotMatch(p,/\\n<\/nav>/);assert.match(fs.readFileSync('public/js/admin-central-saas.js','utf8'),/data-notificar-loja/);});

test('prospecting excludes generic phone listings and keeps explicit public WhatsApp',async()=>{
 const code=fs.readFileSync('src/services/prospeccao.service.js','utf8');let n=0;const module={exports:{}};const elements=[{type:'node',id:1,tags:{name:'Só telefone',phone:'+55 43 3333-6565'}},{type:'node',id:2,tags:{name:'WhatsApp público','contact:whatsapp':'+55 43 99999-9999'}}];
 vm.runInNewContext(code,{require:p=>require('../src/services/'+p.replace('./','')),  module,AbortController,setTimeout,clearTimeout,fetch:async()=>({ok:true,json:async()=>({elements})})});
 const r=await module.exports.buscarProspeccao({uf:'PR',cidade:'Londrina',categoria:'barbearia'});assert.equal(r.leads.length,1);assert.equal(r.leads[0].nome,'WhatsApp público');assert.equal(r.leads[0].whatsapp,'https://wa.me/5543999999999');
});
