const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'src/services/adminReceitas.service.js'),'utf8');
function harness(){const rows=new Map(),module={exports:{}};const db={from(){let id,amb;return {select(){return this},eq(k,v){if(k==='pagamento_id')id=v;if(k==='ambiente')amb=v;return this},maybeSingle:async()=>({data:rows.get(id+'|'+amb)||null}),upsert(p){rows.set(p.pagamento_id+'|'+p.ambiente,p);return Promise.resolve({error:null})}}}};vm.runInNewContext(source,{module,require:n=>n.includes('supabase')?db:n.includes('/planos')?{obterPlano:()=>null}:{obterSituacaoPlano:async()=>({})},Date,Number,Intl,Set,Map,Promise});return {svc:module.exports,rows};}
const c={loja_id:'shop',plano:'ilimitado'},p={id:'pay1',value:149.9,status:'RECEIVED',paymentDate:'2026-10-04'};
test('confirmação e recebimento do mesmo pagamento não duplicam receita',async()=>{const h=harness();await h.svc.registrar(c,{...p,status:'CONFIRMED'},'PAYMENT_CONFIRMED','production');await h.svc.registrar(c,p,'PAYMENT_RECEIVED','production');assert.equal(h.rows.size,1);const r=h.svc.resumo([...h.rows.values()],new Date('2026-10-04T15:00:00Z'));assert.equal(r.total_centavos,14990);assert.equal(r.clientes_pagantes,1);assert.equal(r.pagamentos,1)});
test('renovações distintas somam, cada cliente só conta uma vez',async()=>{const h=harness();await h.svc.registrar(c,p,'PAYMENT_RECEIVED','production');await h.svc.registrar(c,{...p,id:'pay2'},'PAYMENT_RECEIVED','production');const r=h.svc.resumo([...h.rows.values()]);assert.equal(r.total_centavos,29980);assert.equal(r.clientes_pagantes,1)});
test('sandbox, pendências e acesso manual não viram receita real',async()=>{const h=harness();await h.svc.registrar(c,p,'PAYMENT_RECEIVED','sandbox');await h.svc.registrar(c,{...p,id:'pending',status:'PENDING'},'PAYMENT_CREATED','production');assert.equal(await h.svc.registrar(c,{},'manual','production'),false);const r=h.svc.resumo([...h.rows.values()]);assert.equal(r.total_centavos,0);assert.equal(r.clientes_pagantes,0);assert.equal(r.testes,1)});
test('estorno total remove receita; evento antigo não desfaz estorno',async()=>{const h=harness();await h.svc.registrar(c,p,'PAYMENT_RECEIVED','production');await h.svc.registrar(c,{...p,status:'REFUNDED'},'PAYMENT_REFUNDED','production');await h.svc.registrar(c,p,'PAYMENT_RECEIVED','production');const r=h.svc.resumo([...h.rows.values()]);assert.equal(r.total_centavos,0);assert.equal(h.rows.values().next().value.status,'REFUNDED')});
test('valor é o pagamento real e não preço público; parcial deduz do total',async()=>{const h=harness();await h.svc.registrar(c,{...p,refundedValue:20},'PAYMENT_RECEIVED','production');assert.equal(h.svc.resumo([...h.rows.values()]).total_centavos,12990)});
test('dia e mês seguem São Paulo, não o UTC do servidor',()=>{const h=harness(),rows=[{...p,pagamento_id:p.id,loja_id:'shop',ambiente:'production',valor_centavos:14990,estornado_centavos:0,pago_em:'2026-10-01T01:30:00Z'}];const r=h.svc.resumo(rows,new Date('2026-10-01T02:00:00Z'));assert.equal(r.hoje_centavos,14990);assert.equal(r.mes_centavos,14990);assert.equal(h.svc.resumo(rows,new Date('2026-10-01T04:00:00Z')).mes_centavos,0)});
test('todas as rotas financeiras exigem admin e sync usa somente GET no Asaas',()=>{const routes=fs.readFileSync(path.join(root,'src/routes/admin.routes.js'),'utf8');for(const line of routes.split('\n').filter(x=>/central-saas/.test(x)))assert.match(line,/exigirAdmin/);const s=fs.readFileSync(path.join(root,'src/services/asaas.service.js'),'utf8').split('async function sincronizarReceitas')[1];assert.match(s,/method:'GET'/);assert.doesNotMatch(s,/method:'POST'/);assert.match(s,/external_reference===p.externalReference/)});
test('leitura paginada não perde registros depois de mil linhas',async()=>{const module={exports:{}},all=Array.from({length:1100},(_,i)=>({id:i}));vm.runInNewContext(source,{module,require:n=>n.includes('supabase')?{from:()=>({select(){return this},order(){return this},range:async(a,b)=>({data:all.slice(a,b+1)})})}:{},Date,Intl,Set,Map});assert.equal((await module.exports.todos('lojas','id')).length,1100)});
test('painel inclui cadastro público, preço exclusivo e uso por cliente sem confundir acesso com receita',async()=>{const module={exports:{}},tables={lojas:[{id:'a',nome:'Cliente público',ativa:true},{id:'b',nome:'Teste',ativa:true}],assinaturas:[{id:'s1',loja_id:'a',plano:'basico',status:'ativo',valido_ate:null,criado_em:'2026-01-01'},{id:'s2',loja_id:'b',plano:'trial',status:'inativo',valido_ate:null,criado_em:'2026-01-01'}],saintsai_condicoes_comerciais:[{loja_id:'a',plano:'basico',preco_mensal_centavos:9900}],saintsai_receitas_planos:[{pagamento_id:'p1',loja_id:'a',cliente_id:'a',plano:'basico',ambiente:'production',valor_centavos:9900,status:'RECEIVED',pago_em:'2026-10-04'}]};const db={from:t=>({select(){return this},order(){return this},range:async(a,b)=>({data:tables[t].slice(a,b+1)})})};vm.runInNewContext(source,{module,require:n=>n.includes('supabase')?db:n.includes('/planos')?{obterPlano:c=>({nome:c,precoMensalCentavos:20000})}:{obterSituacaoPlano:async()=>({usadoNoMes:900,restanteNoMes:100,plano:{limiteMensagensMes:1000},ativo:true})},Date,Intl,Number,Set,Map,Promise});const x=await module.exports.painel({filtro:'ativos'});assert.equal(x.resumo.clientes,2);assert.equal(x.resumo.ativos,1);assert.equal(x.resumo.clientes_pagantes,1);assert.equal(x.clientes.length,1);assert.equal(x.clientes[0].mensalidade_centavos,9900);assert.equal(x.clientes[0].uso.restante,100);assert.equal(x.recebimentos[0].cliente,'Cliente público');await assert.rejects(()=>module.exports.painel({pagina:0}),/filtro_invalido/)});
test('pagamentos não somem quando o cliente é removido; pendência antiga não desfaz recebimento',async()=>{const h=harness();await h.svc.registrar(c,p,'PAYMENT_RECEIVED','production');await h.svc.registrar(c,{...p,status:'PENDING'},'PAYMENT_CREATED','production');const r=h.rows.values().next().value;r.loja_id=null;const s=h.svc.resumo([r]);assert.equal(s.total_centavos,14990);assert.equal(s.clientes_pagantes,1)});
