const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const plans=[{codigo:'trial',vendavel:false},{codigo:'basico',vendavel:true,precoMensalCentavos:20000,limiteMensagensMes:1000},{codigo:'ilimitado',vendavel:true,precoMensalCentavos:90000,limiteMensagensMes:null}];
function load(p,deps,extra={}){const module={exports:{}};vm.runInNewContext(read(p),{module,exports:module.exports,require:n=>{if(n in deps)return deps[n];throw Error('Missing '+n);},Date,Number,Object,console,...extra});return module.exports;}
function harness(){const rows=new Map();let fail=false;const db={from(){let id,payload,remove=false;return {select(){return this},eq(k,v){id=v;return this},maybeSingle:async()=>({data:rows.get(id)||null,error:fail?Error('db offline'):null}),upsert(p){payload=p;id=p.loja_id;return this},delete(){remove=true;return this},then(resolve){if(!fail){if(remove)rows.delete(id);else rows.set(id,payload);}return Promise.resolve({error:fail?Error('db offline'):null}).then(resolve)}}}};const svc=load('src/services/condicoesComerciais.service.js',{'../config/supabase':db,'../config/planos':{obterPlano:c=>plans.find(p=>p.codigo===c),listarPlanos:()=>plans}});return {svc,rows,db,set fail(x){fail=x}};}
const response=()=>({statusCode:200,status(n){this.statusCode=n;return this},json(x){this.body=x;return this}});
test('condição permanece isolada por empresa e conserva limite ilimitado',async()=>{const h=harness();await h.svc.salvar('a',{tipo:'personalizado',plano:'ilimitado',preco_mensal_centavos:14990},'owner');const a=await h.svc.planoParaLoja('a','ilimitado'),b=await h.svc.planoParaLoja('b','ilimitado');assert.equal(a.precoMensalCentavos,14990);assert.equal(a.limiteMensagensMes,null);assert.equal(b.precoMensalCentavos,90000);assert.equal(plans[2].precoMensalCentavos,90000);assert.equal((await h.svc.planoParaLoja('a','basico')).precoMensalCentavos,20000)});
test('preço exclusivo persiste para cobranças futuras e pode voltar ao público',async()=>{const h=harness();await h.svc.salvar('a',{tipo:'personalizado',plano:'basico',preco_mensal_centavos:9900},'owner');assert.equal((await h.svc.listar('a'))[1].precoMensalCentavos,9900);await h.svc.salvar('a',{tipo:'publico',plano:'basico'},'owner');assert.equal((await h.svc.listar('a'))[1].precoMensalCentavos,20000)});
test('validação rejeita negativos, zero, frações, strings e planos não comerciais',()=>{const {svc}=harness();for(const cents of [-1,0,1.5,'9900',NaN,100000001])assert.throws(()=>svc.validar({tipo:'personalizado',plano:'basico',preco_mensal_centavos:cents}),/condicao_invalida/);assert.throws(()=>svc.validar({tipo:'publico',plano:'trial'}));assert.throws(()=>svc.cadastro({tipo:'publico',plano:'basico',ativar:true,duracao_meses:2}));});
test('falha no banco impede substituir silenciosamente o preço acordado',async()=>{const h=harness();h.fail=true;await assert.rejects(()=>h.svc.planoParaLoja('a','basico'),/db offline/)});
test('validade mensal mantém último dia em meses curtos',()=>{const h=harness();assert.equal(h.svc.validade(1,new Date('2026-01-31T12:00:00Z')),'2026-02-28T12:00:00.000Z')});
test('rotas de cadastro e preço exigem administrador; metadados do cliente não concedem acesso',()=>{const route=read('src/routes/admin.routes.js');for(const line of route.split('\n').filter(s=>/planos-cadastro|condicao-comercial|post\('\/clientes'/.test(s)))assert.match(line,/exigirAdmin/);const auth=load('src/middleware/admin.js',{}, {process:{env:{SAAS_ADMIN_EMAILS:'owner@example.test'}}});const res=response();let next=false;auth.exigirAdmin({usuario:{email:'client@example.test',user_metadata:{admin:true},app_metadata:{admin:true}}},res,()=>next=true);assert.equal(res.statusCode,403);assert.equal(next,false)});
function adminHarness(){const h=harness();let writes=0,assignment,deleted=false;const db={from(){return {insert(){writes++;return this},select(){return this},single:async()=>({data:{id:'shop',nome:'Loja'}}),delete(){deleted=true;return this},eq:async()=>({})}}};const svc=load('src/controllers/admin.controller.js',{'../config/supabase':db,'../config/supabaseAuth':{auth:{admin:{createUser:async()=>{writes++;return {data:{user:{id:'client'}}}},deleteUser:async()=>{deleted=true;}}}},'../middleware/admin':{usuarioEhAdmin:()=>true},'../config/planos':{listarPlanos:()=>plans},'../services/assinaturas.service':{definirAssinatura:async(id,x)=>{assignment=x;},obterSituacaoPlano:async()=>({})},'../utils/validacao':{ehUuid:()=>true},'../services/condicoesComerciais.service':h.svc});return {...h,ctl:svc,get writes(){return writes},get assignment(){return assignment},get deleted(){return deleted}};}
const req=c=>({usuario:{id:'owner'},body:{nome:'Loja Teste',email:'client@example.test',senha:'senha123',condicao_comercial:c}});
test('cadastro inválido é rejeitado antes de criar usuário',async()=>{const h=adminHarness(),res=response();await h.ctl.criarCliente(req({tipo:'personalizado',plano:'basico',preco_mensal_centavos:-1}),res);assert.equal(res.statusCode,400);assert.equal(h.writes,0)});
test('cadastro atribui plano ativo e preço próprio sem registrar pagamento',async()=>{const h=adminHarness(),res=response();await h.ctl.criarCliente(req({tipo:'personalizado',plano:'ilimitado',preco_mensal_centavos:19900,duracao_meses:3,ativar:true}),res);assert.equal(res.statusCode,201);assert.equal(h.assignment.plano,'ilimitado');assert.equal(h.assignment.status,'ativo');assert.equal(res.body.ativacao_manual,true);assert.equal(h.rows.get('shop').preco_mensal_centavos,19900);assert.equal(h.assignment.provider_status,undefined)});
test('falha em condição compensa criação da conta',async()=>{const h=adminHarness();h.svc.salvar=async()=>{throw Error('offline')};const res=response();await h.ctl.criarCliente(req({tipo:'publico',plano:'basico',duracao_meses:1,ativar:false}),res);assert.equal(res.statusCode,500);assert.equal(h.deleted,true)});
test('Pix cobra valor salvo multiplicado pelo período; checkout usa o mesmo preço',async()=>{let amount,insert;const db={from(){return {insert(p){insert=p;return Promise.resolve({})}}}};const asa=load('src/services/asaas.service.js',{'../config/supabase':db,'../config/planos':{obterPlano:c=>plans.find(p=>p.codigo===c)},'./assinaturas.service':{},'./condicoesComerciais.service':{planoParaLoja:async()=>({...plans[2],precoMensalCentavos:14990})}},{process:{env:{ASAAS_API_KEY:'fixture',PUBLIC_BASE_URL:'https://fixture.test',ASAAS_PIX_ADDRESS_KEY:'fixture-key'}},AbortController,Buffer,setTimeout,clearTimeout,fetch:async(url,opt)=>{const payload=JSON.parse(opt.body||'{}');amount=payload.value||payload.items?.[0].value;return {ok:true,text:async()=>JSON.stringify(url.includes('addressKeys')?{data:[{status:'ACTIVE',key:'fixture-key'}]}:{id:'fixture',payload:'fixture-pix',link:'https://fixture.test'})}}});const x=await asa.criarPixPlano({lojaId:'shop',planoCodigo:'ilimitado',duracaoMeses:3});assert.equal(amount,449.7);assert.equal(x.valor_centavos,44970);assert.equal(insert.valor_centavos,44970);await asa.criarCheckoutAssinatura({lojaId:'shop',planoCodigo:'ilimitado'});assert.equal(amount,149.9);assert.equal(insert.valor_centavos,14990);assert.equal(insert.duracao_meses,1)});
test('compra pública mantém preço comum e renovação usa condição da loja',()=>{const source=read('src/services/asaas.service.js').split('async function criarPixCompraPublica')[1];assert.match(source,/obterPlano\(planoCodigo\)/);assert.doesNotMatch(source.split('\nasync function ')[0],/comercial\.planoParaLoja/);assert.match(read('src/services/renovacao.service.js'),/await comercial.listar\(lojaId\)/)});
