const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function harness(){let row=null,stored,mode='APPROVED',env='production',hookFail=false;const calls=[],updates=[];
 const db={from(){let payload;return {select(){return this},eq(){return this},maybeSingle:async()=>({data:row}),update(p){payload=p;updates.push(p);return this},upsert(p){payload=p;row={...(row||{}),...p};return this},then(resolve){return Promise.resolve({error:null,data:row}).then(resolve)}}},rpc:async(n,args)=>{if(n==='saintsai_store_payment_secret'){stored=args.p_secret;return {data:'secret-1'}}return {data:null}}};
 const sub={cfg:()=>({rootKey:'root-fixture',ambiente:env,publicBase:'https://fixture.example'}),obterApiKeyLoja:async()=>'$aact_prod_fixture_key_123456789',tokenWebhook:id=>'token-'+id,criarSubconta:async()=>({ok:true}),req:async(p,opt={},key)=>{calls.push({p,opt,key});if(p.includes('status')){if(mode==='FAIL')throw Error('network');return {general:mode,commercialInfo:'APPROVED',documentation:mode==='APPROVED'?'APPROVED':'PENDING',bankAccountInfo:'PENDING'};}if(p.includes('documents'))return {data:[{description:'Documento do titular',status:'PENDING',onboardingUrl:'https://www.asaas.com/onboarding/fixture'},{description:'Bad link',status:'PENDING',onboardingUrl:'https://attacker.example/fixture'}]};if(p.includes('webhooks')){if(opt.method&&hookFail)throw Error('webhook');return opt.method?{id:'webhook-1'}:{data:[]};}}};
 const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/services/asaasOnboarding.service.js'),'utf8'),{module,exports:module.exports,require:n=>n.includes('supabase')?db:sub,URL,Date,Map,Set});
 return {svc:module.exports,calls,updates,get row(){return row},set row(x){row=x},set mode(x){mode=x},set env(x){env=x},set hookFail(x){hookFail=x},get stored(){return stored}};
}
test('conta nova não consulta outras contas ou afirma aprovação',async()=>{const h=harness(),s=await h.svc.status('loja1');assert.equal(s.conectado,false);assert.equal(s.verificado,false);assert.equal(h.calls.length,0)});
test('conexão não é confundida com aprovação e somente links Asaas chegam ao cliente',async()=>{const h=harness();h.row={provedor:'asaas',conectado:true,provedor_secret_id:'secret'};h.mode='PENDING';const s=await h.svc.status('loja1');assert.equal(s.verificado,true);assert.equal(s.cadastro.general,'PENDING');assert.equal(s.documentos[0].url,'https://www.asaas.com/onboarding/fixture');assert.equal(s.documentos[1].url,null);assert(!JSON.stringify(s).includes('fixture_key'));assert.equal(h.updates[0].provedor_status,'PENDING')});
test('consulta com erro preserva conexão e não publica aprovação antiga como confirmada',async()=>{const h=harness();h.row={provedor:'asaas',conectado:true,provedor_status:'APPROVED',provedor_secret_id:'secret'};h.mode='FAIL';const s=await h.svc.status('loja1');assert.equal(s.conectado,true);assert.equal(s.verificado,false);assert.equal(s.cadastro,null)});
test('conta existente registra webhook antes de salvar a chave protegida e não devolve segredos',async()=>{const h=harness(),key='$aact_prod_fixture_key_123456789';const r=await h.svc.connect('loja1',{chave_api:key,email:'titular@example.test'});assert.equal(r.conectado,true);assert.equal(JSON.parse(h.stored).apiKey,key);assert.equal(h.row.aceita_pix_online,false);const hook=h.calls.find(x=>x.opt.method==='POST');assert.equal(hook.opt.body.url,'https://fixture.example/api/pagamentos/asaas/subconta/webhook');assert.equal(hook.opt.body.authToken,'token-loja1');assert(!JSON.stringify(r).includes(key))});
test('falha do webhook não publica conexão concluída',async()=>{const h=harness();h.hookFail=true;await assert.rejects(()=>h.svc.connect('loja1',{chave_api:'$aact_prod_fixture_key_123456789',email:'titular@example.test'}));assert.equal(h.stored,undefined);assert.equal(h.row,null)});
test('conta conectada não é substituída; chave de teste não entra em produção',async()=>{const h=harness();h.row={conectado:true};await assert.rejects(()=>h.svc.connect('loja1',{chave_api:'$aact_prod_fixture_key_123456789',email:'titular@example.test'}),/conta_ja_conectada/);h.row=null;await assert.rejects(()=>h.svc.connect('loja1',{chave_api:'$aact_hmlg_fixture_key_123456789',email:'titular@example.test'}),/ambiente_incompativel/);assert.equal(h.calls.length,0)});
test('links com credenciais, javascript ou domínios parecidos são rejeitados',()=>{const h=harness();for(const u of ['javascript:alert(1)','https://asaas.com.attacker.test/x','https://user:pass@www.asaas.com/x','http://www.asaas.com/x'])assert.equal(h.svc.safeUrl(u),null)});
function saveHarness(current){let payload;const db={from(){return {select(){return this},eq(){return this},maybeSingle:async()=>({data:current}),upsert(p){payload=p;return this},single:async()=>({data:payload})}}};const module={exports:{}};const source=fs.readFileSync(path.join(__dirname,'../src/controllers/clienteHub.controller.js'),'utf8').match(/async function salvarPagamentos\(req,res\)\{[\s\S]*?(?=function asaasBase)/)[0];vm.runInNewContext(source+'\nmodule.exports=salvarPagamentos;',{module,supabase:db,exigirLoja:async()=>({id:'shop1'}),console});return {save:module.exports,get payload(){return payload}};}
const response=()=>({statusCode:200,status(n){this.statusCode=n;return this},json(body){this.body=body;return this}});
test('salvar dinheiro ou sinal preserva a conta conectada da loja',async()=>{const h=saveHarness({provedor:'asaas',conectado:true}),r=response();await h.save({body:{provedor:'asaas',aceita_dinheiro:true,sinal_tipo:'fixo',sinal_valor:20}},r);assert.equal(r.statusCode,200);assert.equal(h.payload.conectado,true);assert.equal(h.payload.loja_id,'shop1');assert.equal(h.payload.aceita_dinheiro,true)});
test('salvar opções não troca silenciosamente uma conta conectada',async()=>{const h=saveHarness({provedor:'asaas',conectado:true}),r=response();await h.save({body:{provedor:'pagbank'}},r);assert.equal(r.statusCode,400);assert.equal(h.payload,undefined)});
test('chaves legadas e JSON protegido podem ser usadas sem expor segredo ao navegador',async()=>{const source=fs.readFileSync(path.join(__dirname,'../src/services/asaasSubconta.service.js'),'utf8').match(/async function obterApiKeyLoja\(lojaId\)\{[\s\S]*?(?=async function status)/)[0];for(const secret of ['legacy-key',JSON.stringify({apiKey:'legacy-key'})]){const module={exports:{}};vm.runInNewContext(source+'\nmodule.exports=obterApiKeyLoja;',{module,obterConfig:async()=>({provedor:'asaas',conectado:true,provedor_secret_id:'secret'}),supabase:{rpc:async()=>({data:secret})}});assert.equal(await module.exports('shop1'),'legacy-key')}});
