const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync('patches/assets/chatterbox-voice.service.js','utf8');
function fixture({error=false,foreign=false,badAudio=false}={}){const calls=[],m={exports:{}};const wav=Buffer.alloc(100);wav.write('RIFF');wav.write('WAVE',8);let n=0;vm.runInNewContext(code,{module:m,process:{env:{}},URL,AbortSignal,Buffer,fetch:async(url,opts)=>{calls.push({url,opts});n++;if(n===1)return{ok:true,json:async()=>({components:[{type:'audio',props:{label:'Reference Audio File (Optional)',value:{path:'/tmp/reference.wav'}}}]})};if(n===2)return{ok:true,json:async()=>({event_id:'abc'})};if(n===3)return{ok:true,text:async()=>error?'event: error\ndata: "quota"\n\n':'event: complete\ndata: '+JSON.stringify([{url:(foreign?'https://foreign.example':'https://resembleai-chatterbox-multilingual-tts-pt-br.hf.space')+'/gradio_api/file=output.wav'}])+'\n\n'};return{ok:true,headers:{get:()=>null},arrayBuffer:async()=>badAudio?Buffer.alloc(100):wav};}});return{api:m.exports,calls};}
test('uses the demo feminine reference, fixed PT-BR model endpoint and a valid WAV',async()=>{const f=fixture(),b=await f.api.gerar('Olá!');assert.equal(b.length,100);const args=JSON.parse(f.calls[1].opts.body).data;assert.equal(args[1].path,'/tmp/reference.wav');assert.deepEqual(args.slice(2),[0.5,0.8,42,0.5]);});
test('shared quota failure never silently substitutes another voice or retries',async()=>{const f=fixture({error:true});await assert.rejects(()=>f.api.gerar('Olá!'),/indisponivel/);assert.equal(f.calls.length,3);});
test('rejects external download origins and invalid audio',async()=>{let f=fixture({foreign:true});await assert.rejects(()=>f.api.gerar('Olá!'),/origem_invalida/);assert.equal(f.calls.length,3);f=fixture({badAudio:true});await assert.rejects(()=>f.api.gerar('Olá!'),/audio_invalido/);});
test('keeps speech within demo limit, removes links and prefers complete sentences',()=>{const f=fixture(),s='Esta frase explica o atendimento do negócio de forma simples e natural. ';const result=f.api.falaCurta(s.repeat(8));assert(result.length<=300);assert(result.endsWith('.'));assert.equal(f.api.falaCurta('**Oi!** https://example.com'),'Oi!');assert.throws(()=>f.api.falaCurta(' '),/vazio/);});
test('audio only on explicit request; WAV and confirmed WhatsApp receipt required',()=>{const s=fs.readFileSync('patches/assets/sales-voice-chatterbox.service.js','utf8');assert(s.includes('if(!pedidoAudio)'));assert(s.includes("mimetype:'audio/wav'"));assert(s.includes("if(!receipt?.id)"));assert(!s.includes('EdgeTTS'));});
test('one-off real send protects owner, test marker, existing checkout and fixed contact',()=>{const s=fs.readFileSync('patches/assets/chatterbox-test-once.service.js','utf8');for(const marker of ['__saintsai_test','SAINTSAI_OWNER_USER_ID','saintsai_sales_onboarding','cfg.identificador_externo!==c.session_id',"const CONTACT='554396431742@c.us'"])assert(s.includes(marker));assert(s.indexOf('reservarEventoWhatsapp')<s.indexOf('voice.enviarWaha'));assert(s.indexOf('voice.enviarWaha')<s.indexOf('concluirEventoWhatsapp'));});
