const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),express=require('express');
process.env.SUPABASE_URL='https://fixture.supabase.co';
const shop='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',other='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',cfg='cccccccc-cccc-cccc-cccc-cccccccccccc';
const media=require('../patches/assets/galeriaMedia.service'),busca=require('../patches/assets/galeriaBusca.helpers');
const uuid=x=>/^[a-f0-9-]{36}$/.test(x||'');
function load(path,mocks){const m={exports:{}};vm.runInNewContext(fs.readFileSync(path,'utf8'),{module:m,Buffer,URL,process,console,require:p=>Object.hasOwn(mocks,p)?mocks[p]:require(p)});return m.exports;}
function row(id,descricao,tipo='video',extras={}){return{id,loja_id:shop,tipo,descricao,etiquetas:[],ativo:true,storage_bucket:media.BUCKET,arquivo_path:shop+'/'+id+(tipo==='video'?'.mp4':'.jpg'),criado_em:'2026-10-06',...extras};}
const ids=[1,2,3,4].map(n=>'dddddddd-dddd-dddd-dddd-'+String(n).padStart(12,'0'));
test('cada mídia exige descrição; etiquetas são limitadas e deduplicadas',()=>{for(const descricao of ['', ' ', 'x'.repeat(501)])assert.throws(()=>media.detalhes({descricao}));assert.throws(()=>media.detalhes({descricao:'teste',etiquetas:Array.from({length:13},(_,i)=>String(i))}));assert.equal(media.detalhes({descricao:' Camisa ',etiquetas:'oversized, oversized, estampa'}).etiquetas.length,2);});
test('seleção exige todas as características e o tipo solicitado',()=>{const rows=[row(ids[0],'Camisas oversized estampadas'),row(ids[1],'Camisas oversized lisas'),row(ids[2],'Camisas estampadas tradicionais'),row(ids[3],'Camisas oversized estampadas','foto')];const p=busca.pedido('me manda vídeo das camisetas oversize estampadas');assert.deepEqual(busca.selecionar(rows,p).map(x=>x.id),[ids[0]]);});
test('etiquetas relacionam categorias e negações não entregam estampa indevida',()=>{const rows=[row(ids[0],'Coleção verão'),row(ids[1],'Camisa oversized sem estampa'),row(ids[2],'Camisa oversized estampada')];rows[0].tipo='video';rows[0].etiquetas=['camisa','oversized','estampada'];assert.deepEqual(busca.selecionar(rows,busca.pedido('vídeo camisa oversized estampada')).map(x=>x.id),[ids[0],ids[2]]);assert.deepEqual(busca.selecionar(rows,busca.pedido('vídeo camisa oversized sem estampa')).map(x=>x.id),[ids[1]]);});
test('mais usa contexto do cliente e exclui enviados; resposta do agente não escolhe categoria',()=>{const p=busca.pedido('manda mais',[{role:'user',content:'Vídeos de camisas oversized estampadas'},{role:'assistant',content:'Calças azuis'}]);assert.equal(p.tipos[0],'video');assert.deepEqual(busca.selecionar([row(ids[0],'Camisas oversized estampadas'),row(ids[1],'Camisas oversized estampadas')],p,[ids[0]]).map(x=>x.id),[ids[1]]);assert.equal(busca.pedido('manda fotos',[{role:'assistant',content:'Camisas oversized'}]).positivos.length,0);for(const t of ['não quero vídeos','não envie mais','pare de enviar mais','qual o preço?'])assert.equal(busca.pedido(t),null);});
test('URL deriva do arquivo próprio e recusa outra empresa ou endereço arbitrário',()=>{assert(media.url(row(ids[0],'Camisa'),shop).startsWith(process.env.SUPABASE_URL));assert.equal(media.url(row(ids[0],'Camisa','video',{loja_id:other}),shop),null);assert.equal(media.url(row(ids[0],'Camisa','video',{arquivo_path:'https://evil.test/a.mp4'}),shop),null);});
function fixture(){const rows=new Map(),uploads=[],removed=[];let fail=false,n=0;const db={from(){let filters=[],op='select',values;const q={select(){return q},eq(k,v){filters.push([k,v]);return q},not(){return q},order(){return q},range(){return q},or(){return q},insert(v){op='insert';values=v;return q},update(v){op='update';values=v;return q},delete(){op='delete';return q},single(){return Promise.resolve(result())},maybeSingle(){return Promise.resolve(result())},then(resolve){resolve({data:[...rows.values()],count:rows.size})}};function result(){if(op==='insert'){const r={...values,id:ids[n++],arquivo_path:null};rows.set(r.id,r);return{data:r};}const r=[...rows.values()].find(r=>filters.every(([k,v])=>r[k]===v));if(!r)return{data:null};if(op==='update')Object.assign(r,values);if(op==='delete')rows.delete(r.id);return{data:{...r}};}return q},storage:{from:()=>({upload:async(path,b)=>{uploads.push(path);return fail?{error:Error('offline')}:{data:{path}}},remove:async paths=>{removed.push(...paths);return{data:[]}}})}};
const c=load('patches/assets/galeria.controller.js',{'../config/supabase':db,'../services/galeriaMedia.service':media,'../utils/validacao':{ehUuid:uuid},'./clienteVideo.controller':{mp4Valido:b=>b.includes(Buffer.from('avc1'))}});
const mount=load('patches/assets/galeria.routes.js',{'express':express,'../controllers/galeria.controller':c,'../services/galeriaMedia.service':media,'../middleware/auth':{exigirLogin:(req,res,next)=>req.headers.authorization?next():res.sendStatus(401)},'../middleware/lojaOwnership':{exigirDonoDaLoja:(req,res,next)=>req.params.lojaId===shop?next():res.sendStatus(403)}});const app=express();mount(app);app.use((e,req,res,next)=>res.status(e.status||500).json({erro:'request'}));return{app,rows,uploads,removed,setFail:v=>fail=v};}
async function run(fn){const x=fixture(),server=x.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{await fn(x,'http://127.0.0.1:'+server.address().port+'/api/lojas/'+shop+'/galeria');}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}}
const json=(method,body)=>({method,headers:{authorization:'Bearer fixture','content-type':'application/json'},body:JSON.stringify(body)});
function jpeg(n=200*1024){const b=Buffer.alloc(n);b[0]=255;b[1]=216;b[2]=255;return b;}
const binary=b=>({method:'POST',headers:{authorization:'Bearer fixture','content-type':'image/jpeg'},body:b});
test('API cria vários arquivos na mesma categoria e descrição obrigatória',()=>run(async(x,base)=>{assert.equal((await fetch(base,json('POST',{tipo:'foto',descricao:''}))).status,400);for(let i=0;i<2;i++){const r=await fetch(base,json('POST',{tipo:'foto',descricao:'Camisas oversized estampadas'}));assert.equal(r.status,201);const m=await r.json();assert.equal((await fetch(base+'/'+m.id+'/arquivo',binary(jpeg()))).status,201);}assert.equal(x.rows.size,2);assert.equal(x.uploads.length,2);}));
test('login e propriedade são verificados antes de receber arquivos grandes',()=>run(async(x,base)=>{const noauth=binary(jpeg());delete noauth.headers.authorization;assert.equal((await fetch(base+'/'+ids[0]+'/arquivo',noauth)).status,401);assert.equal((await fetch(base.replace(shop,other)+'/'+ids[0]+'/arquivo',binary(jpeg()))).status,403);assert.equal((await fetch(base+'/'+ids[0]+'/arquivo',binary(jpeg()))).status,404);assert.equal(x.uploads.length,0);}));
test('falha preserva descrição para tentar novamente; edição pausa e limites recusam arquivo',()=>run(async(x,base)=>{const m=await (await fetch(base,json('POST',{tipo:'foto',descricao:'Camisa estampada'}))).json();const path=base+'/'+m.id+'/arquivo';x.setFail(true);assert.equal((await fetch(path,binary(jpeg()))).status,500);assert.equal(x.rows.get(m.id).descricao,'Camisa estampada');x.setFail(false);assert.equal((await fetch(path,binary(jpeg()))).status,201);assert.equal((await fetch(path,binary(jpeg(3*1024*1024+1)))).status,413);assert.equal((await fetch(path,binary(Buffer.alloc(32)))).status,400);assert.equal((await fetch(base+'/'+m.id,json('PUT',{descricao:'Camisa nova',ativo:false}))).status,200);assert.equal(x.rows.get(m.id).ativo,false);assert.equal((await fetch(base+'/'+m.id,json('PUT',{descricao:' '}))).status,400);}));
function senderFixture(){let states={},fixed=null,sent=[],ackFail=false;const records=ids.slice(0,3).map(id=>row(id,'Camisas oversized estampadas'));const db={from:t=>{let filters=[];const q={select(){return q},eq(k,v){filters.push([k,v]);return q},maybeSingle:async()=>({data:t==='whatsapp_fila_processamento'?{id:ids[3]}:records.find(m=>filters.every(([k,v])=>m[k]===v))})};return q},rpc:async(name,p)=>{if(!fixed)fixed=p.p_itens;const m=fixed[p.p_indice];if(!m)return{data:{enviar:false}};const i=p.p_indice;if(p.p_acao==='claim'){if(states[i])return{data:{enviar:false,midia:m,estado:states[i]}};states[i]='enviando';return{data:{enviar:true,midia:m,estado:'enviando'}};}if(ackFail)return{error:Error('ack failed')};states[i]=p.p_acao==='ack'?'enviado':'ignorado';return{data:{enviar:false,midia:m,estado:states[i]}};}};
const service=load('patches/assets/galeriaEnvio.service.js',{'../config/supabase':db,'./galeriaMedia.service':media,'../utils/validacao':{ehUuid:uuid}});const msg={lojaId:shop,configuracaoId:cfg,contato:'5543999999999',idExterno:'input'},res={lojaId:shop,contato:msg.contato,idExterno:'input',resposta:'Seleção\nCamisas',midias:records.map(m=>({...m,url:'https://evil.test/video.mp4'}))};return{service,msg,res,sent,send:async(m,r)=>sent.push(r),setAckFail:v=>ackFail=v,states};}
test('envio usa URL própria revalidada e não repete arquivos confirmados',async()=>{const x=senderFixture();await x.service.enviar(x.msg,x.res,{provedor:'waha'},x.send);assert.equal(x.sent.length,3);assert(x.sent.every(r=>r.videoUrl.startsWith(process.env.SUPABASE_URL)));await x.service.enviar(x.msg,x.res,{provedor:'waha'},x.send);assert.equal(x.sent.length,3);});
test('falha na confirmação não repete entrega incerta, mas envia arquivos ainda não tentados',async()=>{const x=senderFixture();x.setAckFail(true);await assert.rejects(()=>x.service.enviar(x.msg,x.res,{provedor:'waha'},x.send));assert.equal(x.sent.length,1);x.setAckFail(false);await assert.rejects(()=>x.service.enviar(x.msg,x.res,{provedor:'waha'},x.send),/não reenviar/);assert.equal(x.sent.length,3);await assert.rejects(()=>x.service.enviar(x.msg,x.res,{provedor:'waha'},x.send));assert.equal(x.sent.length,3);});
test('galeria ocupa centro da navegação e requer descrição no formulário',()=>{const html=fs.readFileSync('patches/assets/cliente-galeria.html','utf8');assert.match(html,/Galeria/);assert.match(html,/required/);const nav=html.slice(html.lastIndexOf('<nav'));assert(nav.indexOf('cliente-produtos')<nav.indexOf('cliente-galeria'));assert(nav.indexOf('cliente-galeria')<nav.indexOf('cliente-agenda'));});
test('atendimento limita três arquivos e consulta somente loja, configuração e contato próprios',async()=>{const filters=[];const records=ids.map(id=>row(id,'Camisas oversized estampadas'));const db={from:t=>{const q={select(){return q},eq(k,v){filters.push([t,k,v]);return q},in(){return q},order(){return q},limit:async()=>({data:t==='saintsai_galeria'?records:[{galeria_envios:{itens:[{id:ids[0]}],estados:{0:'enviado'}}}]})};return q}};const service=load('patches/assets/galeriaAtendimento.service.js',{'../config/supabase':db,'./galeriaMedia.service':media,'./galeriaBusca.helpers':busca});let r=await service.tentar({lojaId:shop,configuracaoId:cfg,contato:'5543999999999',texto:'vídeos camisas oversized estampadas'},[]);assert.equal(r.midias.length,3);r=await service.tentar({lojaId:shop,configuracaoId:cfg,contato:'5543999999999',texto:'mais'},[{role:'user',content:'vídeos camisas oversized estampadas'}]);assert.equal(r.midias.length,3);assert(!r.midias.some(m=>m.id===ids[0]));assert(filters.some(([t,k,v])=>t==='whatsapp_fila_processamento'&&k==='configuracao_id'&&v===cfg));assert(filters.some(([t,k,v])=>t==='whatsapp_fila_processamento'&&k==='contato'&&v==='5543999999999'));r=await service.tentar({lojaId:shop,texto:'vídeos'},[]);assert(!r.midias);assert.match(r.resposta,/qual produto/);r=await service.tentar({lojaId:shop,texto:'vídeo calças azuis'},[]);assert(!r.midias);assert.match(r.resposta,/Não encontrei/);});
