const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),express=require('express');
const id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
function fixture(){let calls=0;const uploads=new Map(),meta={};const db={from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{id,nome:'Empresa',dono_id:'owner'}})})})}),storage:{getBucket:async()=>({data:{id:'servico-imagens'}}),from:()=>({upload:async(p,b)=>{calls++;uploads.set(p,b);return {};},download:async p=>({data:uploads.get(p),error:uploads.has(p)?null:Error('missing')}),getPublicUrl:p=>({data:{publicUrl:'https://fixture.test/'+p}})})}};const auth={auth:{admin:{getUserById:async()=>({data:{user:{user_metadata:meta}}}),updateUserById:async(user,p)=>{Object.assign(meta,p.user_metadata);return {data:{user:{user_metadata:meta}}};}}}};const login=(req,res,next)=>{if(req.headers.authorization!=='Bearer fixture')return res.status(401).json({erro:'login'});req.usuario={id:'owner'};next();};const owner=(req,res,next)=>req.params.lojaId===id?next():res.status(403).json({erro:'ownership'});
 function load(path){const m={exports:{}};vm.runInNewContext(fs.readFileSync(path,'utf8'),{module:m,Buffer,console,require:p=>p==='express'?express:p.includes('lojaOwnership')?{exigirDonoDaLoja:owner}:p.endsWith('/auth')?{exigirLogin:login}:p.includes('/middleware/admin')?{usuarioEhAdmin:()=>false}:p.includes('supabaseAuth')?auth:p.includes('supabase')?db:require(p)});return m.exports;}
 const app=express();load('patches/assets/imageUploadParsers.js')(app);app.use(express.json({limit:'100kb'}));const upload=load('patches/assets/servicoImagem.controller.js'),marca=load('patches/assets/clienteMarca.controller.js');app.post('/api/lojas/:lojaId/servico-imagem',upload.upload);app.post('/api/lojas/:lojaId/produto-imagem',upload.upload);app.put('/api/lojas/:lojaId/cliente-hub/marca',login,owner,marca.salvar);app.get('/api/lojas/:lojaId/cliente-hub/marca',login,owner,marca.obter);app.post('/ordinary',(_req,res)=>res.json({ok:true}));app.use((e,_req,res,_next)=>res.status(e.type==='entity.too.large'?413:500).json({erro:e.type}));return {app,uploads,calls:()=>calls};}
async function run(fn){const x=fixture(),server=x.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{await fn(x,'http://127.0.0.1:'+server.address().port);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}}
const req=(method,body,token=true)=>({method,headers:{'content-type':'application/json',...(token?{authorization:'Bearer fixture'}:{})},body:JSON.stringify(body)});
test('foto acima de 100 KB chega ao upload e salva como perfil, consultável depois',()=>run(async(x,base)=>{const bytes=Buffer.alloc(300*1024,42),url='data:image/png;base64,'+bytes.toString('base64');const u=await fetch(base+'/api/lojas/'+id+'/servico-imagem',req('POST',{data_url:url}));assert.equal(u.status,201);const p=await u.json();assert(x.uploads.get(p.imagem_path).equals(bytes));const s=await fetch(base+'/api/lojas/'+id+'/cliente-hub/marca',req('PUT',{nome:'Minha empresa',imagem_path:p.imagem_path}));assert.equal(s.status,200);const g=await fetch(base+'/api/lojas/'+id+'/cliente-hub/marca',{headers:{authorization:'Bearer fixture'}});const brand=await g.json();assert.equal(brand.nome,'Minha empresa');assert.equal(brand.imagem_path,p.imagem_path);}));
test('produto recebe corpo grande; outras APIs continuam limitadas a 100 KB',()=>run(async(x,base)=>{const data_url='data:image/png;base64,'+Buffer.alloc(150*1024).toString('base64');assert.equal((await fetch(base+'/api/lojas/'+id+'/produto-imagem',req('POST',{data_url}))).status,201);assert.equal((await fetch(base+'/ordinary',req('POST',{data_url}))).status,413);}));
test('limite de 3 MB na imagem e 5 MB na requisição continuam ativos',()=>run(async(x,base)=>{for(const n of [3*1024*1024+1,4*1024*1024]){const r=await fetch(base+'/api/lojas/'+id+'/servico-imagem',req('POST',{data_url:'data:image/png;base64,'+Buffer.alloc(n).toString('base64')}));assert.equal(r.status,413);}assert.equal(x.calls(),0);}));
test('upload exige login e acesso à empresa antes de processar a foto',()=>run(async(x,base)=>{const body={data_url:'data:image/png;base64,'+Buffer.alloc(150*1024).toString('base64')};assert.equal((await fetch(base+'/api/lojas/'+id+'/servico-imagem',req('POST',body,false))).status,401);assert.equal((await fetch(base+'/api/lojas/bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb/servico-imagem',req('POST',body))).status,403);assert.equal(x.calls(),0);}));
