const test=require('node:test'),assert=require('node:assert/strict');
const {criarAdaptadorWaha}=require('../src/services/providers/whatsapp/adaptadorWaha');
const input={canal:'whatsapp',lojaId:'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',configuracaoId:'bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb',contato:'5543999999999@c.us',texto:'Demonstração: 1) Pix 2) Cartão',interativo:{type:'button',action:{buttons:['Pix','Cartão'].map(title=>({type:'reply',reply:{id:'sa:'+Buffer.from(title).toString('base64url'),title}}))}}};
function fixture(status){const calls=[];const adapter=criarAdaptadorWaha({baseUrl:'https://waha.test',apiKey:'fake',session:'test-session',fetchFn:async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});return {ok:url.endsWith('/api/sendText')||status===201,status,json:async()=>({key:{id:'receipt'}})};}});return{adapter,calls};}
test('QR sends actual buttons through the provider instead of discarding interactive content',async()=>{const f=fixture(201),r=await f.adapter.enviarMensagem(input);assert.equal(r.status,'enviado');assert.equal(f.calls.length,1);assert(f.calls[0].url.endsWith('/api/sendList'));assert.equal(f.calls[0].body.message.sections[0].rows[0].title,'Pix');assert.equal(f.calls[0].body.chatId,input.contato);assert.equal(r.idExterno,'receipt');});
test('explicit unsupported format sends one usable numbered text menu',async()=>{const f=fixture(422),r=await f.adapter.enviarMensagem(input);assert.equal(r.status,'enviado');assert.equal(f.calls.length,2);assert(f.calls[1].url.endsWith('/api/sendText'));assert.match(f.calls[1].body.text,/1\) Pix/);});
for(const status of [429,500])test('ambiguous/unavailable button delivery does not send a second message '+status,async()=>{const f=fixture(status),r=await f.adapter.enviarMensagem(input);assert.notEqual(r.status,'enviado');assert.equal(f.calls.length,1);});
test('new incoming job is immediately claimable; it never waits for a fictitious processing lease',async()=>{
 const fs=require('node:fs'),vm=require('node:vm'),m={exports:{}};let inserted;
 const db={from:()=>({insert:x=>{inserted=x;return{select:()=>({single:async()=>({data:{id:'cccccccc-cccc-4ccc-cccc-cccccccccccc'}})})}}})};
 vm.runInNewContext(fs.readFileSync('src/services/whatsappFila.service.js','utf8'),{module:m,process:{env:{}},Date,require:n=>n==='../config/supabase'?db:require('../src/utils/validacao')});
 const job=await m.exports.enfileirarMensagemWhatsapp({...input,texto:'Me manda algum botão de pagamento',idExterno:'incoming-unique'},{provedor:'waha',destinatarioId:'session'});assert.equal(job.status,'pendente');assert.equal(inserted.tentativas,0);assert.equal(inserted.lease_ate,null);assert(Date.now()-new Date(inserted.proxima_tentativa_em)<1000);
});
test('NOWEB native menu click becomes the selected payment, even without a body',()=>{const p=require('../src/services/providers/whatsapp/interpretadorWebhookWaha');const event=p.interpretarPayloadWebhookWaha({event:'message',session:'test-session',payload:{id:'unique-list-click',from:input.contato,fromMe:false,_data:{message:{listResponseMessage:{singleSelectReply:{selectedRowId:'Pix'}}}}}});assert.equal(event.texto,'Pix');assert.equal(event.contato,input.contato);});
