const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function place(i,more={}){return{id:String(i),displayName:{text:'Barbearia '+i},internationalPhoneNumber:'+55 44 99999-'+String(i).padStart(4,'0'),businessStatus:'OPERATIONAL',rating:4,userRatingCount:i*10,formattedAddress:'Maringá PR',addressComponents:[{types:['administrative_area_level_2'],longText:'Maringá'},{types:['administrative_area_level_1'],shortText:'PR'}],...more}}
function harness(o={}){let calls=0,checks=0;const db={from(t){const q={select(){return q},eq(){return q},limit(){return q},maybeSingle:async()=>({data:{dono_id:o.foreign?'other':'owner'}}),then(resolve,reject){return Promise.resolve({data:o.disconnected?[]:[{provedor:'waha',identificador_externo:'session',numero_whatsapp:'5544999999999'}]}).then(resolve,reject)}};return q}};const module={exports:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../patches/assets/maps-prospecting.service'),'utf8'),{require:n=>({'./municipios-br':[['PR','Maringá',-23,-51]],'./prospeccao.service':{CATEGORIAS:{barbearia:{label:'Barbearia'}}},'../config/supabase':db,'./ownerProspecting.service':{chatPorTelefone:async(session,phone)=>{checks++;if(o.notWhatsapp)throw Object.assign(Error(),{status:400});if(o.connectionError)throw Object.assign(Error(),{status:503});return phone+'@c.us'}}}[n]),module,process:{env:{GOOGLE_MAPS_API_KEY:o.noKey?'':'secret',SAINTSAI_OWNER_USER_ID:'owner'}},fetch:async(url,options)=>{calls++;assert.equal(url,'https://places.googleapis.com/v1/places:searchText');assert(!JSON.stringify(JSON.parse(options.body)).includes('secret'));assert.equal(JSON.parse(options.body).pageSize,20);return{ok:!o.apiError,json:async()=>({places:o.places||Array.from({length:18},(_,i)=>place(i+1))})}},AbortSignal,Error,Math,Map,Number,String,Promise});return{...module.exports,get calls(){return calls},get checks(){return checks}}}
const args={uf:'PR',cidade:'Maringá',categoria:'barbearia',lojaId:'shop',usuario:{id:'owner'}};
test('até 10 contatos reais sem exigir site; ordem decrescente e origem Maps',async()=>{const h=harness();const r=await h.buscarProspeccao(args);assert.equal(r.leads.length,10);assert.equal(r.origem,'Google Maps');assert(r.leads.every(x=>x.site===''&&x.whatsapp));assert(r.leads.every((x,i)=>!i||r.leads[i-1].score>=x.score));assert(h.checks>=10)});
test('remove duplicados, fechados, telefones fixos, sem telefone e outra cidade',async()=>{const h=harness({places:[place(1),place(1),place(2,{businessStatus:'CLOSED_PERMANENTLY'}),place(3,{internationalPhoneNumber:'+55 44 3222 0000'}),place(4,{internationalPhoneNumber:''}),place(5,{addressComponents:[]})]});assert.equal((await h.buscarProspeccao(args)).leads.length,1)});
test('não inventa dez opções quando apenas uma existe',async()=>{assert.equal((await harness({places:[place(1)]}).buscarProspeccao(args)).leads.length,1)});
test('não lista número sem WhatsApp',async()=>{assert.equal((await harness({notWhatsapp:true}).buscarProspeccao(args)).leads.length,0)});
for(const flag of ['noKey','foreign','disconnected'])test(flag+' falha antes de chamar Google',async()=>{const h=harness({[flag]:true});await assert.rejects(h.buscarProspeccao(args));assert.equal(h.calls,0)});
for(const flag of ['apiError','connectionError'])test(flag+' retorna erro claro sem dados inventados',async()=>{await assert.rejects(harness({[flag]:true}).buscarProspeccao(args))});
test('cidade inválida e usuário alheio bloqueados',async()=>{const h=harness();await assert.rejects(h.buscarProspeccao({...args,cidade:'inexistente'}));await assert.rejects(h.buscarProspeccao({...args,usuario:{id:'other'}}));assert.equal(h.calls,0)});
