const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function harness(o={}){const module={exports:{}};let calls=0;const leads=o.leads||Array.from({length:20},(_,i)=>({id:String(i),nome:'Negócio '+i,telefone:'554499999'+String(i).padStart(4,'0'),score:50+i,whatsapp_publicado:i%2===0,whatsapp:'https://wa.me/554499999'+String(i).padStart(4,'0')}));const db={from(t){const q={select(){return q},eq(){return q},limit(){return q},maybeSingle:async()=>({data:{dono_id:o.foreign?'other':'owner'}}),then(resolve,reject){return Promise.resolve({data:o.noQR?[]:[{provedor:'waha',identificador_externo:'session'}]}).then(resolve,reject)}};return q}};vm.runInNewContext(fs.readFileSync(require.resolve('../patches/assets/osm-prospecting.service'),'utf8'),{module,require:n=>({'./prospeccao.service':{buscarProspeccao:async()=>({leads,origem:'OpenStreetMap/Overpass',local:'Maringá PR'})},'../config/supabase':db,'./ownerProspecting.service':{chatPorTelefone:async()=>{calls++;if(o.notWhatsapp)throw Object.assign(Error(),{status:400});if(o.unavailable)throw Object.assign(Error(),{status:503});return'chat@lid'}}}[n]),Map,Promise,String,Error});return{...module.exports,get calls(){return calls}}}
const args={uf:'PR',cidade:'Maringá',categoria:'barbearia',lojaId:'shop',usuario:{id:'owner'}};
test('busca sem chave Google, até dez opções verificadas por ordem decrescente',async()=>{const h=harness(),r=await h.buscarProspeccao(args);assert.equal(r.leads.length,10);assert(r.leads.every((x,i)=>!i||r.leads[i-1].score>=x.score));assert(r.leads.every(x=>x.whatsapp_status==='Confirmado na sua conexão'));assert(h.calls>=10)});
test('offset entrega outro lote sem duplicar contatos e encerra quando não há mais',async()=>{const h=harness(),a=await h.buscarProspeccao(args),b=await h.buscarProspeccao({...args,offset:a.nextOffset});assert(a.nextOffset>0&&a.nextOffset<20);assert.equal(a.hasMore,true);assert.equal(b.hasMore,false);assert(b.leads.length<=10);assert.equal(a.leads.some(x=>b.leads.some(y=>x.telefone===y.telefone)),false)});
test('sem QR mostra apenas WhatsApps publicados, até dez, sem exigir conexão',async()=>{const h=harness({noQR:true});const r=await h.buscarProspeccao(args);assert(r.leads.length>0&&r.leads.length<=10);assert(r.leads.every(x=>x.whatsapp_publicado));assert.equal(h.calls,0)});
test('sem loja selecionada ainda permite busca de contatos publicados',async()=>{const r=await harness().buscarProspeccao({...args,lojaId:undefined});assert(r.leads.length>0&&r.leads.length<=10)});
test('não mostra telefone que falhou na confirmação de WhatsApp',async()=>{assert.equal((await harness({notWhatsapp:true}).buscarProspeccao(args)).leads.length,0)});
test('falha na conexão preserva só WhatsApps publicados com aviso honesto',async()=>{const r=await harness({unavailable:true}).buscarProspeccao(args);assert(r.leads.every(x=>x.whatsapp_publicado));assert.match(r.aviso,/não puderam ser confirmados/)});
test('loja de outro dono é bloqueada',async()=>{const h=harness({foreign:true});await assert.rejects(h.buscarProspeccao(args),e=>e.status===403);assert.equal(h.calls,0)});
test('duplicados não ocupam posições; nunca completa com opções inventadas',async()=>{const lead={nome:'Barbearia',telefone:'5544999999999',whatsapp_publicado:true,score:90};const r=await harness({leads:[lead,lead]}).buscarProspeccao({...args,lojaId:undefined});assert.equal(r.leads.length,1)});
