const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const path=require('node:path');
const asset=n=>fs.readFileSync(path.join(__dirname,'../patches/assets',n),'utf8');
function load(source,deps,extra={}){const m={exports:{}};vm.runInNewContext(source,{module:m,exports:m.exports,require:n=>deps[n]||(n==='./ownerSellerTest.service'?{isTest:()=>false}:require(n)),process:{env:{SAINTSAI_OWNER_USER_ID:'owner',SUPABASE_SERVICE_ROLE_KEY:'test-only-key',PUBLIC_BASE_URL:'https://example.test',...extra.env}},Buffer,Date,Intl,setTimeout,console,...extra});return m.exports;}
function fixture(){
 const tables={lojas:[{id:'owner-store',dono_id:'owner'}],saintsai_sales_conversations:[{id:'conv',loja_id:'owner-store',contato:'phone',ativo:true,ultimo_evento_id:'prospeccao:iniciado:1',lead_status:'prompt_pronta',briefing:{nome_empresa:'Camisas da Ana',ramo:'roupas'},prompt_rascunho:'Only sell registered shirts.'}],saintsai_sales_onboarding:[],cobrancas_assinaturas:[]};let creates=0,charges=0,paid=false,createdUser=null,provisionPrompt='';
 class Q{constructor(t){this.t=t;this.filters=[];this.kind='read';}select(){return this;}eq(k,v){this.filters.push(x=>x[k]===v);return this;}limit(){return this;}order(){return this;}insert(v){this.kind='insert';this.v=v;return this;}update(v){this.kind='update';this.v=v;return this;}async single(){const r=await this.run();return {...r,data:r.data[0]||null};}maybeSingle(){return this.single();}then(a,b){return this.run().then(a,b);}async run(){const items=tables[this.t]||=[];let rows=items.filter(x=>this.filters.every(f=>f(x)));if(this.kind==='insert'){if(this.t==='saintsai_sales_onboarding'&&items.some(x=>x.conversa_id===this.v.conversa_id))return {error:{code:'23505'},data:[]};const row={id:'onboarding-'+items.length,...this.v};items.push(row);rows=[row];}if(this.kind==='update')rows.forEach(x=>Object.assign(x,this.v));return {data:rows.map(x=>({...x})),error:null};}}
 const db={from:t=>new Q(t),async rpc(name,p){assert.equal(name,'saintsai_provision_sales_account');const row=tables.saintsai_sales_onboarding.find(x=>x.id===p.p_onboarding);assert.equal(row.phase,'creating');row.customer_store_id=p.p_store;row.phase='payment_method';provisionPrompt=p.p_prompt;tables.lojas.push({id:p.p_store,dono_id:p.p_user,nome:p.p_name,prompt_mestre:p.p_prompt});return {data:p.p_store,error:null};},auth:{admin:{async createUser(v){creates++;createdUser=v;assert.equal(v.app_metadata.saintsai_first_access,true);assert.ok(v.email.endsWith('.invalid'));return {data:{user:{id:'customer'}},error:null};},async getUserById(){return {data:{user:{app_metadata:{saintsai_first_access:true}}}};}}}};
 const billing={configurado:()=>true,webhookConfigurado:()=>true,ambiente:()=> 'production',async criarPixPlano(v){charges++;assert.equal(v.duracaoMeses,1);return {provider_qr_id:'qr',pix_copia_cola:'fake-qr',valor_centavos:9900,ambiente:'production',expira_em:new Date(Date.now()+86400000).toISOString()};},async criarCheckoutAssinatura(){charges++;return {provider_checkout_id:'checkout',checkout_url:'https://example.test/pay',ambiente:'production'};}};
 const subs={async definirAssinatura(id,v){assert.equal(v.status,'inativo');},async buscarAssinaturaAtual(){return {status:paid?'ativo':'inativo'};}};
 const service=load(asset('owner-sales-onboarding.service.js'),{'../config/supabase':db,'../config/planos':{listarPlanos:()=>[{codigo:'basico',nome:'Básico',descricao:'Plano registrado',vendavel:true,precoMensalCentavos:9900}]},'./asaas.service':billing,'./assinaturas.service':subs,'./businessProfiles.service':require('../src/services/businessProfiles.service'),'./ownerSalesPrompt':require('../patches/assets/owner-sales-prompt')});return {service,tables,billing,creates:()=>creates,charges:()=>charges,user:()=>createdUser,prompt:()=>provisionPrompt,setPaid:()=>{paid=true;tables.cobrancas_assinaturas.push({loja_id:tables.saintsai_sales_onboarding[0].customer_store_id,provider_checkout_id:'qr',status_provider:'PAYMENT_CONFIRMED'});}};
}
const args=pergunta=>({lojaId:'owner-store',contato:'phone',pergunta});
test('registered price, explicit plan, one account and one charge even on repeated or simultaneous input',async()=>{const f=fixture();let r=await f.service.handle(args('quero saber'));assert.match(r.response,/99,00/);assert.equal(f.creates(),0);await Promise.all([f.service.handle(args('basico')),f.service.handle(args('basico'))]);assert.equal(f.creates(),1);assert.equal(f.user().app_metadata.saintsai_business_profile,'roupas');assert.match(f.prompt(),/Categoria confirmada: Loja de roupas/);assert.equal(f.tables.saintsai_sales_onboarding[0].phase,'payment_method');await Promise.all([f.service.handle(args('pix')),f.service.handle(args('pix'))]);assert.equal(f.charges(),1);assert.equal(f.tables.saintsai_sales_onboarding[0].phase,'awaiting_payment');r=await f.service.handle(args('paguei'));assert.match(r.response,/Ainda aguardamos/);assert.equal(f.charges(),1);assert.ok(!JSON.stringify(f.tables.saintsai_sales_onboarding).includes('Senha temporária'));f.setPaid();r=await f.service.handle(args('paguei'));assert.match(r.response,/Pagamento confirmado/);assert.equal(f.tables.saintsai_sales_onboarding[0].phase,'active');});
test('tenant and unselected contacts cannot provision a client',async()=>{const f=fixture();f.tables.lojas[0].dono_id='someone';assert.equal((await f.service.handle(args('basico'))).handled,false);assert.equal(f.creates(),0);f.tables.lojas[0].dono_id='owner';f.tables.saintsai_sales_conversations[0].ultimo_evento_id='personal';assert.equal((await f.service.handle(args('basico'))).handled,false);await assert.rejects(()=>f.service.list({id:'other'},'owner-store'));});
test('sandbox is blocked and ambiguous charge is not retried',async()=>{const f=fixture();await f.service.handle(args('basico'));f.billing.ambiente=()=> 'sandbox';assert.match((await f.service.handle(args('pix'))).response,/produção/);assert.equal(f.charges(),0);f.billing.ambiente=()=> 'production';f.billing.criarPixPlano=async()=>{throw Error('timeout after charge');};assert.match((await f.service.handle(args('pix'))).response,/conferir/);assert.equal(f.tables.saintsai_sales_onboarding[0].phase,'needs_owner');assert.match((await f.service.handle(args('pix'))).response,/revisão/);});
test('decline during briefing thanks once, pauses and never collects it as an answer',async()=>{const f=fixture();f.tables.saintsai_sales_conversations[0].lead_status='briefing';f.tables.saintsai_sales_onboarding.push({id:'onb',conversa_id:'conv',owner_store_id:'owner-store',phase:'briefing'});const r=await f.service.handle(args('Obrigado, não temos interesse no momento.'));assert.equal(r.response,'Agradeço por responder. Tenha um ótimo dia!');assert.equal(f.tables.saintsai_sales_onboarding[0].phase,'declined');assert.equal(f.tables.saintsai_sales_conversations[0].ativo,false);assert.equal(f.creates(),0);});
test('refusal detector handles common polite and explicit declines without matching unrelated answers',()=>{const {recusou}=require('../patches/assets/owner-sales-prompt');for(const s of ['Não queremos agora','Obrigado, não temos interesse no momento','Não me mande mais mensagens','Por enquanto não','Não, obrigado'])assert.equal(recusou(s),true,s);for(const s of ['Não temos equipe','Não conheço o SaintsAI','Agora estamos ocupados'])assert.equal(recusou(s),false,s);});
test('seller only handles SaintsAI topics and leaves unrelated questions unanswered',async()=>{const {relacionadaAoSaintsai}=require('../patches/assets/owner-sales-prompt');for(const s of ['Como funciona o atendimento pelo WhatsApp?','Quanto custa o plano?','Tenho uma loja de roupas','Quero ver uma demonstração','Somos uma clínica odontológica'],'Consigo\nPq','Consigo por que?')assert.equal(relacionadaAoSaintsai(s),true,s);for(const s of ['Vai chover amanhã?','Quem ganhou o jogo?','Me explique a inflação'])assert.equal(relacionadaAoSaintsai(s),false,s);const f=fixture();let r=await f.service.handle(args('Qual vai ser a previsão do tempo amanhã?'));assert.equal(r.handled,true);assert.equal(r.response,null);assert.equal(await f.service.after(args('Qual vai ser a previsão do tempo amanhã?'),null),null);f.tables.saintsai_sales_onboarding.push({id:'onb',conversa_id:'conv',owner_store_id:'owner-store',phase:'offer'});r=await f.service.handle(args('Qual vai ser a previsão do tempo amanhã?'));assert.equal(r.handled,true);assert.equal(r.response,null);assert.equal(f.tables.saintsai_sales_onboarding[0].phase,'offer');});
test('seller anti-flood never drops a valid answer because it arrived quickly or repeats',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/services/salesSeller.service.js'),'utf8');assert.doesNotMatch(source,/antiflood_intervalo|ms<6000|antirepeticao_bloqueada/);assert.match(source,/filtrarAntiFlood\(lojaId,contato,respostaTexto\)/);assert.match(source,/silencio_modelo_resposta_segura/);assert.match(source,/silencio_fora_do_escopo/);});
test('first access cannot promote an account or change another user; reauth required',async()=>{let updates=0;const db={auth:{admin:{async updateUserById(id,v){updates++;assert.equal(id,'client');assert.equal(v.app_metadata.saintsai_first_access,false);return {data:{user:{id}}};},async signOut(){return {};}}}};const ctrl=load(asset('first-access.controller.js'),{'../config/supabase':db,'../middleware/admin':{emailsAdmin:()=>['owner@example.test']},'@supabase/supabase-js':{createClient:()=>({auth:{async signInWithPassword(v){if(v.password==='wrong')return {error:{status:400}};return {data:{user:{id:'client'},session:{access_token:'new',refresh_token:'refresh'}}};}}})}},{setTimeout:fn=>fn()});const req={usuario:{id:'client',email:'temp@acesso.saintsai.invalid',app_metadata:{saintsai_first_access:true}},headers:{authorization:'Bearer temp'},body:{email:'owner@example.test',senha:'new-password',senha_temporaria:'old',id:'owner'}};const res={status(n){this.code=n;return this;},json(x){this.body=x;return this;},set(){}};await ctrl.concluir(req,res);assert.equal(res.code,400);assert.equal(updates,0);req.body.email='client@example.test';req.body.senha_temporaria='wrong';await ctrl.concluir(req,res);assert.equal(res.code,403);assert.equal(updates,0);req.body.senha_temporaria='old';await ctrl.concluir(req,res);assert.equal(updates,1);assert.equal(res.body.ok,true);});
test('server gate enforces onboarding and rejects pre-change access JWTs',async()=>{let user={id:'client',app_metadata:{saintsai_first_access:true}};const ctrl=load(fs.readFileSync(path.join(__dirname,'../src/middleware/auth.js'),'utf8'),{'../config/supabase':{auth:{getUser:async()=>({data:{user}})}}});const req={headers:{authorization:'Bearer x.'+Buffer.from(JSON.stringify({iat:1})).toString('base64url')+'.x'},originalUrl:'/api/lojas'};const res={status(n){this.code=n;return this;},json(x){this.body=x;return this;}};let next=0;await ctrl.exigirLogin(req,res,()=>next++);assert.equal(res.code,403);assert.equal(res.body.code,'FIRST_ACCESS_REQUIRED');req.originalUrl='/api/auth/primeiro-acesso/status';await ctrl.exigirLogin(req,res,()=>next++);assert.equal(next,1);user={id:'client',app_metadata:{saintsai_first_access:false,saintsai_credentials_after:2}};req.originalUrl='/api/lojas';await ctrl.exigirLogin(req,res,()=>next++);assert.equal(res.code,401);assert.equal(next,1);});

test('active customer receives specific setup help without repeating temporary credentials',async()=>{const f=fixture();await f.service.handle(args('basico'));await f.service.handle(args('pix'));f.setPaid();await f.service.handle(args('paguei'));for(const [question,expected] of [['como conecto meu WhatsApp?',/Aparelhos conectados/],['como recebo por Pix?',/própria conta Asaas/],['como adiciono fotos?',/Galeria/]]){const r=await f.service.handle(args(question));assert.match(r.response,expected);assert(!r.response.includes('Senha temporária'));}assert.equal(f.creates(),1);assert.equal(f.charges(),1);});
