const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const code=fs.readFileSync(path.join(__dirname,'../patches/assets/owner-seller-test.service.js'),'utf8');
function fixture(){let sends=0,real=false,running=false;const events=new Set(),rows=[],saved=[];class Q{constructor(t){this.t=t;this.filters=[];}select(){return this;}eq(k,v){this.filters.push(x=>x[k]===v);return this;}limit(){return this;}order(){return this;}update(v){this.v=v;return this;}upsert(v){this.up=v;return this;}async maybeSingle(){const r=await this.run();return {...r,data:r.data[0]||null};}then(a,b){return this.run().then(a,b);}async run(){let data=this.t==='lojas'?[{id:'store',dono_id:'owner'}]:this.t==='whatsapp_configuracoes'?[{id:'cfg',provedor:'waha',identificador_externo:'session',numero_whatsapp:'5543999999999'}]:this.t==='saintsai_sales_conversations'?rows:this.t==='saintsai_sales_onboarding'?(real?[{id:'real'}]:[]):this.t==='whatsapp_eventos_processados'?[{status:'concluido'}]:this.t==='whatsapp_fila_processamento'?(running?[{id:'pending'}]:[]):[];if(this.t==='lojas')data=data.filter(x=>this.filters.every(f=>f(x)));if(this.up){Object.assign(rows[0]||(rows[0]={id:'conv'}),this.up);saved.push(this.up);data=rows;}if(this.v){data.forEach(x=>Object.assign(x,this.v));saved.push(this.v);}return {data:data.map(x=>({...x})),error:null};}}
 const db={from:t=>new Q(t)},m={exports:{}};vm.runInNewContext(code,{module:m,process:{env:{SAINTSAI_OWNER_USER_ID:'owner',WAHA_BASE_URL:'https://fake',WAHA_API_KEY:'fake'}},AbortSignal,Date,Set,Error,fetch:async()=>({ok:true,json:async()=>({status:'WORKING',me:{id:'5543999999999@c.us'}})}),require:n=>n==='../config/supabase'?db:n==='./ownerProspecting.service'?{chatPorTelefone:async()=> 'contact@lid'}:n==='./whatsappIdempotencia.service'?{reservarEventoWhatsapp:async e=>{if(events.has(e.idExterno))return false;events.add(e.idExterno);return true;},concluirEventoWhatsapp:async()=>{}}:n==='./whatsappEnvio.service'?{enviarRespostaWhatsapp:async()=>{sends++;return {status:'enviado'};}}:n==='./ownerSalesPrompt'?{INTRO:'Intro',MASTER:'Master'}:n==='./ownerSalesOnboarding.service'?{available:()=>[{codigo:'basico',nome:'Básico'}],offer:()=> 'Básico 99'}:require(n)});return {svc:m.exports,rows,saved,sends:()=>sends,setReal:()=>real=true,setRunning:()=>running=true};}
const id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',id2='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
test('each new click resets briefing and sends one introduction; network retry does not repeat',async()=>{const f=fixture();await f.svc.restart({id:'owner'},{lojaId:'store',requestId:id});assert.equal(f.sends(),1);assert.equal(f.rows[0].briefing.__saintsai_test,true);f.rows[0].briefing.nome_empresa='Old answers';await f.svc.restart({id:'owner'},{lojaId:'store',requestId:id});assert.equal(f.sends(),1);assert.equal(f.rows[0].briefing.nome_empresa,'Old answers');await f.svc.restart({id:'owner'},{lojaId:'store',requestId:id2});assert.equal(f.sends(),2);assert.equal(f.rows[0].briefing.nome_empresa,undefined);assert.equal(f.rows[0].briefing_step,0);});
test('foreign owner, actual customer flow and current in-flight response are protected',async()=>{let f=fixture();await assert.rejects(()=>f.svc.restart({id:'other'},{lojaId:'store',requestId:id}));assert.equal(f.sends(),0);f.rows.push({id:'conv'});f.setReal();await assert.rejects(()=>f.svc.restart({id:'owner'},{lojaId:'store',requestId:id}),/contratação real/);assert.equal(f.sends(),0);f=fixture();f.setRunning();await assert.rejects(()=>f.svc.restart({id:'owner'},{lojaId:'store',requestId:id}),/resposta atual/);});
test('test checkout selects plan and simulates payment without real provisioning or billing',async()=>{const f=fixture();const c={id:'conv',lead_status:'prompt_pronta',briefing:{__saintsai_test:true}};f.rows.push(c);let r=await f.svc.handle({pergunta:'basico'},c);assert.match(r.response,/simulados/);assert.equal(c.briefing.__test_phase,'payment');r=await f.svc.handle({pergunta:'pix'},c);assert.match(r.response,/Nenhuma conta nem cobrança real/);assert.equal(c.briefing.__test_phase,'done');assert.equal(f.sends(),0);assert(!f.saved.some(x=>x.customer_store_id));});
test('old jobs are ignored after restart and phone is supplied only by authenticated API',async()=>{const f=fixture();f.rows.push({briefing:{__saintsai_test:true,__test_started:'2026-10-08T00:00:00Z'}});assert.equal(await f.svc.stale({loja_id:'store',contato:'phone',criado_em:'2026-10-07T00:00:00Z'}),true);assert.equal(await f.svc.stale({loja_id:'store',contato:'phone',criado_em:'2026-10-09T00:00:00Z'}),false);assert.throws(()=>f.svc.info({id:'other'}));assert.equal(f.svc.info({id:'owner'}).telefone,'554396431742');assert(!fs.readFileSync(path.join(__dirname,'../patches/assets/admin-vendedor-teste.html'),'utf8').includes('9643'));});
