const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const prompt='Agora eu vou simular que sou um cliente comprando o agente que a gente vende você vai começar a me enviando a mensagem de prospecção e nós vamos fazer todas as etapas menos criar minha conta tudo aqui é fictício me mande a mensagem abordagem';
function fixture(){let state={__saintsai_test:true,__lab_phase:'payment'},calls=[];const m={exports:{}};vm.runInNewContext(fs.readFileSync('patches/assets/owner-free-simulation.service.js','utf8'),{module:m,Date,require:n=>n==='../config/supabase'?{from:()=>({update(v){state=v.briefing;return this},eq:async()=>({error:null})})}:n==='./ownerSalesPrompt'?{INTRO:'Oi! Sou a assistente virtual do SaintsAI. Vocês usam o WhatsApp para receber pedidos ou marcar horários?'}:n==='./ownerSalesOnboarding.service'?{offer:()=> 'Básico: R$100/mês, 1.000 respostas'}:{estaConfigurado:()=>true,gerarResposta:async x=>{calls.push(x);return 'Vamos entender seu negócio. Qual é o nome da sua empresa?'}}});return{service:m.exports,state:()=>state,calls};}
test('actual long instruction resets stale payment phase and begins with original prospecting message',async()=>{const f=fixture(),c={id:'c',briefing:f.state()};assert.equal(f.service.start(prompt),true);let r=await f.service.handle({pergunta:prompt},c);assert.match(r.response,/Vocês usam o WhatsApp/);assert.equal(f.state().__lab_phase,null);assert.equal(f.state().__lab_free,true);assert.equal(f.calls.length,0);r=await f.service.handle({pergunta:'Tenho uma barbearia, vamos continuar'}, {...c,briefing:f.state()});assert.match(r.response,/nome da sua empresa/);assert.equal(f.calls.length,1);assert.match(f.calls[0].contexto.cenario,/fictício/);assert.equal(f.calls[0].historico[0].role,'assistant');assert.equal(f.state().__lab_history.length,3);});
test('free module does not intercept ordinary sales without private simulation state',async()=>{const f=fixture();assert.equal(await f.service.handle({pergunta:'quero comprar'},{id:'c',briefing:{}}),null);assert.equal(f.calls.length,0);});
test('private simulator is unreachable before contact trust check',()=>{const source=fs.readFileSync('patches/assets/owner-product-lab.service.js','utf8');assert(source.indexOf('if(!await trusted(args,c))')<source.indexOf("require('./ownerFreeSimulation.service')"));assert(source.indexOf('Não acessa segredos')<source.indexOf("require('./ownerFreeSimulation.service')"));});

test('gallery capability questions explain implemented upload-and-send without calling model or claiming media generation',async()=>{const f=fixture();const r=await f.service.handle({pergunta:'Tenho loja de roupas, o cliente me pede um vídeo de camisas oversized, a IA consegue mandar ou não?'},{id:'c',briefing:{__lab_free:true,__lab_history:[]}});assert.match(r.response,/consegue enviar fotos e vídeos/);assert.match(r.response,/não cria vídeos novos/);assert.equal(f.calls.length,0);assert.equal(f.state().__lab_history.length,2);});
test('natural restart wording uses original introduction and resets simulation history',async()=>{const f=fixture();const r=await f.service.handle({pergunta:'Vamos começar do zero. Me envie a abordagem inicial'},{id:'c',briefing:{__lab_free:true,__lab_history:[{role:'assistant',content:'old'}]}});assert.match(r.response,/Vocês usam o WhatsApp/);assert.equal(f.calls.length,0);assert.equal(f.state().__lab_history.length,1);});
