const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function fixture({key='$aact_prod_fake',fail=false}={}){let state={},requests=[],creates=0;const m={exports:{}};const db={from:t=>{assert.equal(t,'saintsai_sales_conversations');return{update(v){state=v.briefing;return this},eq(){return this},select(){return this},maybeSingle:async()=>({data:{id:'c'},error:null}),then(a,b){return Promise.resolve({error:null}).then(a,b)}}}};vm.runInNewContext(fs.readFileSync('patches/assets/owner-real-pix-test.service.js','utf8'),{module:m,Date,Intl,console:{error(){}},require:n=>n==='../config/supabase'?db:n==='./ownerSalesOnboarding.service'?{available:()=>[{codigo:'pro',nome:'Pro',precoMensalCentavos:19900}]}:{cfg:()=>({ambiente:'production',rootKey:key}),obterApiKeyLoja:async()=>key,req:async(path,opt)=>{requests.push({path,opt});if(path.includes('addressKeys'))return{data:[{key:'fake-address',status:'ACTIVE'}]};creates++;if(fail)throw Error('timeout');return{id:'qr-real',payload:'provider-payload'}}}});return{service:m.exports,state:()=>state,requests,creates:()=>creates};}
const args={lojaId:'own',contato:'554396431742@c.us',pergunta:'gere o pagamento pix real do modo pro para testar se reconhece no banco'};
test('owner request uses real configured price and production QR without subscription or account writes; repeat reuses QR',async()=>{const f=fixture();let r=await f.service.handle(args,{id:'c',atualizado_em:'timestamp',briefing:{}});assert.match(r.response,/199,00/);assert.match(r.response,/provider-payload/);assert.equal(f.requests[1].opt.body.value,199);assert.equal(f.requests[1].opt.body.expirationSeconds,900);assert.equal(f.requests[1].opt.body.allowsMultiplePayments,false);assert.match(f.requests[1].opt.body.externalReference,/^saintsai_lab:/);assert.equal(f.creates(),1);r=await f.service.handle(args,{id:'c',briefing:f.state()});assert.match(r.response,/provider-payload/);assert.equal(f.creates(),1);});
test('friend or other test operator cannot emit real QR',async()=>{const f=fixture();assert.match((await f.service.handle({...args,contato:'12345@lid'},{briefing:{}})).response,/apenas no número do dono/);assert.equal(f.requests.length,0);});
test('sandbox never masquerades as bank-recognizable production QR',async()=>{const f=fixture({key:'$aact_hmlg_fake'});assert.match((await f.service.handle(args,{briefing:{}})).response,/produção válida/);assert.equal(f.requests.length,0);});
test('ambiguous QR creation is held for review instead of automatically creating again',async()=>{const f=fixture({fail:true});await f.service.handle(args,{id:'c',briefing:{}});assert.equal(f.state().__lab_real_pix_status,'needs_review');await f.service.handle(args,{id:'c',briefing:f.state()});assert.equal(f.creates(),1);});

test('owner dictated centavo request creates exactly one centavo instead of plan price',async()=>{const f=fixture();const q={...args,pergunta:'Me mande uma cobrança dê um picos de um centavo para me confirmar se as notificações e pagamento chegam normal'};await f.service.handle(q,{id:'c',briefing:{}});assert.equal(f.requests[1].opt.body.value,0.01);assert.equal(f.state().__lab_real_pix.centavos,1);});
test('explicit amount does not reuse a different unexpired plan QR',async()=>{const f=fixture();await f.service.handle({...args,pergunta:'Quero gerar Pix real valor de 0,01 para testar'},{id:'c',briefing:{__lab_real_pix:{payload:'wrong-price',centavos:19900,expira:new Date(Date.now()+900000).toISOString()}}});assert.equal(f.requests[1].opt.body.value,0.01);});
