const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function harness(opts={}){
 let sent=0,marked=[],reserved=false,state='processando',active=false;
 const db={from(table){let values;const q={select(){return q},eq(){return q},limit(){return q},update(v){values=v;return q},maybeSingle:async()=>result(),then(resolve,reject){return Promise.resolve(result()).then(resolve,reject)}};function result(){if(values){marked.push(values);if('ativo'in values)active=values.ativo;return{error:null}}if(table==='lojas')return{data:{id:'shop',dono_id:opts.foreign?'other':'owner',prompt_mestre:'meu prompt'}};if(table==='whatsapp_configuracoes')return{data:opts.disconnected?[]:[{id:'cfg',provedor:opts.meta?'meta':'waha',identificador_externo:'session',numero_whatsapp:'5544999999999'}]};return{data:{status:state}}}return q}};
 const dependencies={'../config/supabase':db,'node:crypto':require('node:crypto'),'./ownerSalesPrompt':require('../patches/assets/owner-sales-prompt'),'./ownerProspecting.service':{chatPorTelefone:async()=> '5544999888888@lid',autorizar:async()=>{active=true}},'./whatsappIdempotencia.service':{reservarEventoWhatsapp:async()=>{if(reserved)return false;reserved=true;return true},concluirEventoWhatsapp:async()=>{state='concluido'}},'./whatsappEnvio.service':{enviarRespostaWhatsapp:async(message,response)=>{assert.equal(message.contato,'5544999888888@lid');assert.match(response.resposta,/assistente virtual/);sent++;if(opts.timeout)throw Error('timeout');return{status:opts.simulated?'simulado':'enviado'}}}};
 const module={exports:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../patches/assets/owner-first-message.service'),'utf8'),{require:name=>dependencies[name],module,process:{env:{SAINTSAI_OWNER_USER_ID:'owner',WAHA_BASE_URL:'https://local',WAHA_API_KEY:'mock'}},fetch:async()=>({ok:true,json:async()=>({status:opts.offline?'STOPPED':'WORKING',me:{id:opts.wrongIdentity?'other@c.us':'5544999999999@c.us'}})}),AbortSignal,Error,Date,String});
 return{...module.exports,get sent(){return sent},get active(){return active},marked};
}
const args={lojaId:'shop',telefone:'5544999888888'};
test('envia primeira abordagem uma vez; reabrir não repete e mantém marcador iniciado',async()=>{const h=harness();assert.equal((await h.iniciar({id:'owner'},args)).status,'enviada');assert.equal((await h.iniciar({id:'owner'},args)).status,'ja_enviada');assert.equal(h.sent,1);assert(h.active);assert(h.marked.every(v=>/^prospeccao:iniciado:/.test(v.ultimo_evento_id)));});
test('cliques concorrentes reservam um único envio',async()=>{const h=harness();const r=await Promise.allSettled([h.iniciar({id:'owner'},args),h.iniciar({id:'owner'},args)]);assert.equal(h.sent,1);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);});
for(const option of ['timeout','simulated'])test(option+' não permite repetir envio incerto e pausa IA',async()=>{const h=harness({[option]:true});await assert.rejects(h.iniciar({id:'owner'},args),/confirmar/);await assert.rejects(h.iniciar({id:'owner'},args),/Não será repetida/);assert.equal(h.sent,1);assert.equal(h.active,false)});
for(const option of ['foreign','meta','disconnected','offline','wrongIdentity'])test('bloqueia '+option+' antes de enviar ou autorizar',async()=>{const h=harness({[option]:true});await assert.rejects(h.iniciar({id:'owner'},args));assert.equal(h.sent,0);assert.equal(h.active,false)});
test('bloqueia outro usuário, próprio número e telefone inválido',async()=>{const h=harness();await assert.rejects(h.iniciar({id:'other'},args));await assert.rejects(h.iniciar({id:'owner'},{...args,telefone:'5544999999999'}));await assert.rejects(h.iniciar({id:'owner'},{...args,telefone:'123'}));assert.equal(h.sent,0)});
test('prompt apenas para loja do dono',async()=>{assert.equal(await harness().promptDaLoja('shop'),'meu prompt');assert.equal(await harness({foreign:true}).promptDaLoja('shop'),null)});
