const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const code=fs.readFileSync(path.join(__dirname,'../patches/assets/owner-seller-test.service.js'),'utf8');
function fixture(buttonFail=false){let sends=0,real=false,running=false;const events=new Set(),rows=[],saved=[],buttonRequests=[];class Q{constructor(t){this.t=t;this.filters=[];}select(){return this;}eq(k,v){this.filters.push(x=>x[k]===v);return this;}limit(){return this;}order(){return this;}update(v){this.v=v;return this;}upsert(v){this.up=v;return this;}async maybeSingle(){const r=await this.run();return {...r,data:r.data[0]||null};}then(a,b){return this.run().then(a,b);}async run(){let data=this.t==='lojas'?[{id:'store',dono_id:'owner'}]:this.t==='whatsapp_configuracoes'?[{id:'cfg',provedor:'waha',identificador_externo:'session',numero_whatsapp:'5543999999999'}]:this.t==='saintsai_sales_conversations'?rows:this.t==='saintsai_sales_onboarding'?(real?[{id:'real'}]:[]):this.t==='whatsapp_eventos_processados'?[{status:'concluido'}]:this.t==='whatsapp_fila_processamento'?(running?[{id:'pending'}]:[]):[];if(this.t==='lojas')data=data.filter(x=>this.filters.every(f=>f(x)));if(this.up){assert.equal(this.up.lead_status,'conversa');Object.assign(rows[0]||(rows[0]={id:'conv'}),this.up);saved.push(this.up);data=rows;}if(this.v){data.forEach(x=>Object.assign(x,this.v));saved.push(this.v);}return {data:data.map(x=>({...x})),error:null};}}
 const db={from:t=>new Q(t)},m={exports:{}};vm.runInNewContext(code,{module:m,process:{env:{SAINTSAI_OWNER_USER_ID:'owner',WAHA_BASE_URL:'https://fake',WAHA_API_KEY:'fake'}},AbortSignal,Date,Set,Error,fetch:async(u,o)=>{if(u.endsWith('/api/sendButtons')){buttonRequests.push(JSON.parse(o.body));return{ok:!buttonFail,json:async()=>({id:'sent'})};}return{ok:true,json:async()=>({status:'WORKING',me:{id:'5543999999999@c.us'}})};},require:n=>n==='../config/supabase'?db:n==='./ownerProspecting.service'?{chatPorTelefone:async()=> 'contact@lid'}:n==='./whatsappIdempotencia.service'?{reservarEventoWhatsapp:async e=>{if(events.has(e.idExterno))return false;events.add(e.idExterno);return true;},concluirEventoWhatsapp:async()=>{}}:n==='./whatsappEnvio.service'?{enviarRespostaWhatsapp:async()=>{sends++;return {status:'enviado'};}}:n==='./ownerSalesPrompt'?{INTRO:'Intro',MASTER:'Master'}:n==='./ownerSalesOnboarding.service'?{available:()=>[{codigo:'basico',nome:'Básico'}],offer:()=> 'Básico 99'}:require(n)});return {svc:m.exports,rows,saved,buttonRequests,sends:()=>sends,setReal:()=>real=true,setRunning:()=>running=true};}
const id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',id2='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
test('each new click resets briefing and sends one introduction; network retry does not repeat',async()=>{const f=fixture();await f.svc.restart({id:'owner'},{lojaId:'store',requestId:id});assert.equal(f.sends(),1);assert.equal(f.rows[0].briefing.__saintsai_test,true);f.rows[0].briefing.nome_empresa='Old answers';await f.svc.restart({id:'owner'},{lojaId:'store',requestId:id});assert.equal(f.sends(),1);assert.equal(f.rows[0].briefing.nome_empresa,'Old answers');await f.svc.restart({id:'owner'},{lojaId:'store',requestId:id2});assert.equal(f.sends(),2);assert.equal(f.rows[0].briefing.nome_empresa,undefined);assert.equal(f.rows[0].briefing_step,0);});
test('foreign owner, actual customer flow and current in-flight response are protected',async()=>{let f=fixture();await assert.rejects(()=>f.svc.restart({id:'other'},{lojaId:'store',requestId:id}));assert.equal(f.sends(),0);f.rows.push({id:'conv'});f.setReal();await assert.rejects(()=>f.svc.restart({id:'owner'},{lojaId:'store',requestId:id}),/contratação real/);assert.equal(f.sends(),0);f=fixture();f.setRunning();await assert.rejects(()=>f.svc.restart({id:'owner'},{lojaId:'store',requestId:id}),/resposta atual/);});
test('test checkout selects plan and simulates payment without real provisioning or billing',async()=>{const f=fixture();const c={id:'conv',lead_status:'prompt_pronta',briefing:{__saintsai_test:true}};f.rows.push(c);let r=await f.svc.handle({pergunta:'basico'},c);assert.match(r.response,/simulados/);assert.equal(c.briefing.__test_phase,'payment');r=await f.svc.handle({pergunta:'pix'},c);assert.match(r.response,/Nenhuma conta nem cobrança real/);assert.equal(c.briefing.__test_phase,'done');assert.equal(f.sends(),0);assert(!f.saved.some(x=>x.customer_store_id));});
test('old jobs are ignored after restart and phone is supplied only by authenticated API',async()=>{const f=fixture();f.rows.push({briefing:{__saintsai_test:true,__test_started:'2026-10-08T00:00:00Z'}});assert.equal(await f.svc.stale({loja_id:'store',contato:'phone',criado_em:'2026-10-07T00:00:00Z'}),true);assert.equal(await f.svc.stale({loja_id:'store',contato:'phone',criado_em:'2026-10-09T00:00:00Z'}),false);assert.throws(()=>f.svc.info({id:'other'}));assert.equal(f.svc.info({id:'owner'}).telefone,'554396431742');assert(!fs.readFileSync(path.join(__dirname,'../patches/assets/admin-vendedor-teste.html'),'utf8').includes('9643'));});
test('WhatsApp opens during the click while reset API is still pending',async()=>{
 const nodes={'test-buttons':{disabled:true},store:{value:'store',replaceChildren(){},add(){}},restart:{disabled:true},status:{textContent:'',append(){}},number:{}};let opened=null,resolveReset;const context={document:{getElementById:id=>nodes[id],createElement:()=>({}),createElementNS:()=>({}),createTextNode:()=>({})},window:{AndroidAgent:{openWhatsApp:n=>opened=n}},localStorage:{getItem:()=>null},Option:function(){},crypto:{randomUUID:()=>id},apiFetch:async url=>url.endsWith('/minhas-lojas')?{lojas:[{id:'store',nome:'Store'}]}:url.endsWith('/reiniciar')?new Promise(resolve=>resolveReset=resolve):{telefone:'554396431742',exibicao:'Test'}};context.document.createElement=()=>({});
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../patches/assets/owner-seller-test.js'),'utf8'),context);await new Promise(r=>setImmediate(r));const click=nodes.restart.onclick();assert.equal(opened,'5543996431742');assert.equal(nodes.restart.disabled,true);assert(resolveReset);context.document.createElement=()=>({});resolveReset({telefone:'5543996431742'});await click;assert.equal(nodes.restart.disabled,false);
});

test('experimental cuts menu targets fixed test contact, deduplicates and never provisions bookings',async()=>{const f=fixture();await f.svc.restart({id:'owner'},{lojaId:'store',requestId:id,modo:'botoes',telefone:'attacker'});assert.equal(f.buttonRequests.length,1);assert.equal(f.buttonRequests[0].chatId,'contact@lid');assert.equal(f.buttonRequests[0].buttons.length,3);assert.equal(f.sends(),0);await f.svc.restart({id:'owner'},{lojaId:'store',requestId:id,modo:'botoes'});assert.equal(f.buttonRequests.length,1);let r=await f.svc.handle({pergunta:'Degradê R$35'},f.rows[0]);assert.match(r.response,/pagar no local/);r=await f.svc.handle({pergunta:'pagar no local'},f.rows[0]);assert.match(r.response,/Nenhum horário ou pagamento real/);});
test('unsupported buttons report error and pause test without silently sending text',async()=>{const f=fixture(true);await assert.rejects(()=>f.svc.restart({id:'owner'},{lojaId:'store',requestId:id,modo:'botoes'}),/não foi confirmado/);assert.equal(f.sends(),0);assert.equal(f.rows[0].ativo,false);});

test('ordinary audio request works even after completed simulated checkout',async()=>{const f=fixture(),c={id:'conv',briefing:{__saintsai_test:true,__test_phase:'done'}};const r=await f.svc.handle({pergunta:'Me manda uma mensagem de voz'},c);assert.match(r.response,/agenda configurada/);assert.equal(f.sends(),0);assert.equal(f.saved.length,0);});
test('ordinary buttons request uses test session and contact and never creates a charge',async()=>{const f=fixture(),c={id:'conv',session_id:'session',contato:'fixed-test',briefing:{__saintsai_test:true,__test_phase:'done'}};f.rows.push(c);const r=await f.svc.handle({pergunta:'Me mostra os botões'},c);assert.match(r.response,/demonstração/);assert.equal(f.buttonRequests[0].chatId,'fixed-test');assert.equal(c.briefing.__test_phase,'cuts');assert.equal(f.sends(),0);});
test('ordinary buttons failure preserves test phase and reports lack of confirmation',async()=>{const f=fixture(true),c={id:'conv',session_id:'session',contato:'fixed-test',briefing:{__saintsai_test:true,__test_phase:'done'}};const r=await f.svc.handle({pergunta:'Me manda um botão'},c);assert.match(r.response,/Não consegui confirmar/);assert.equal(f.saved.length,0);});
test('natural test requests cannot enable demos in real sales conversations',async()=>{const f=fixture();assert.equal((await f.svc.handle({pergunta:'Me mostra os botões'},{briefing:{}})).handled,false);assert.equal(f.buttonRequests.length,0);});
