const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function deliveryFixture(ack){let queries=0;const m={exports:{}};vm.runInNewContext(fs.readFileSync('patches/assets/waha-delivery.service.js','utf8'),{module:m,require,Buffer,process:{env:{WAHA_BASE_URL:'https://mock',WAHA_API_KEY:'mock'}},fetch:async()=>{queries++;return {ok:true,json:async()=>({ack})}},AbortSignal,setTimeout:fn=>(fn(),0)});return{service:m.exports,queries:()=>queries};}
for(const ack of [-1,0,1,2,3,4])test('delivery acknowledges '+ack+' correctly',async()=>{const h=deliveryFixture(ack);assert.equal(await h.service.check('session','msg'),ack===-1?'failed':ack>=2?'delivered':'pending');assert(h.queries()<=3)});
function flow(estado='delivered',failSend=false){let sent=0,reserved=false,complete=false,active=true,marker='prospeccao:iniciado:1:autoatendimento';const helper=deliveryFixture(0).service,db={from:t=>{let values;const q={select(){return q},eq(){return q},limit(){return q},update(v){values=v;return q},maybeSingle:async()=>result(),then:r=>Promise.resolve(result()).then(r)};function result(){if(values){if(values.ultimo_evento_id)marker=values.ultimo_evento_id;if('ativo'in values)active=values.ativo;return{error:null}}return{data:t==='lojas'?{id:'store',dono_id:'owner'}:t==='whatsapp_configuracoes'?[{id:'cfg',provedor:'waha',identificador_externo:'session',numero_whatsapp:'5544999999999'}]:t==='saintsai_sales_conversations'?{ultimo_evento_id:marker}:{status:complete?'concluido':'processando'}};}return q;}};
 const m={exports:{}},deps={'../config/supabase':db,'node:crypto':require('node:crypto'),'./ownerSalesPrompt':{INTRO:'Intro',MASTER:'Master'},'./ownerProspecting.service':{chatPorTelefone:async()=> '5544999888888@c.us',autorizar:async()=>{active=true}},'./whatsappIdempotencia.service':{reservarEventoWhatsapp:async()=>{if(reserved)return false;reserved=true;return true},concluirEventoWhatsapp:async()=>{complete=true}},'./whatsappEnvio.service':{enviarRespostaWhatsapp:async(_,__,ctx)=>{assert.equal(ctx.confirmarEntrega,true);sent++;if(failSend)throw Error('uncertain');return{status:'enviado',idExternoProvider:'message'}}},'./wahaDelivery.service':{...helper,check:async()=>estado}};
 vm.runInNewContext(fs.readFileSync('patches/assets/owner-first-message-confirmed.service.js','utf8'),{module:m,require:p=>deps[p],process:{env:{SAINTSAI_OWNER_USER_ID:'owner',WAHA_BASE_URL:'https://mock',WAHA_API_KEY:'mock'}},fetch:async()=>({ok:true,json:async()=>({status:'WORKING',me:{id:'5544999999999@c.us'}})}),AbortSignal,Buffer,Date});return{run:()=>m.exports.iniciar({id:'owner'},{lojaId:'store',telefone:'5544999888888'}),sent:()=>sent,active:()=>active,marker:()=>marker};}
test('accepted but pending does not claim delivery or resend on second click',async()=>{const h=flow('pending');assert.equal((await h.run()).status,'pendente_entrega');assert.equal((await h.run()).status,'pendente_entrega');assert.equal(h.sent(),1);assert.match(h.marker(),/:ack:pending:autoatendimento$/);});
test('device confirmation is sent once and preserves automation guard',async()=>{const h=flow();assert.equal((await h.run()).status,'enviada');assert.equal((await h.run()).status,'ja_enviada');assert.equal(h.sent(),1);assert.match(h.marker(),/:ack:delivered:autoatendimento$/);});
test('rejected delivery pauses agent and blocks all repeat sends',async()=>{const h=flow('failed');await assert.rejects(h.run(),/recusou a entrega/);await assert.rejects(h.run(),/recusou a entrega/);assert.equal(h.sent(),1);assert.equal(h.active(),false);assert.match(h.marker(),/:ack:failed:autoatendimento$/);});
test('ambiguous network result never retries automatically',async()=>{const h=flow('pending',true);await assert.rejects(h.run(),/confirmar/);await assert.rejects(h.run(),/Não será repetida/);assert.equal(h.sent(),1);});
test('new category works in source and both user-facing search controls',()=>{const source=fs.readFileSync('src/services/prospeccao.service.js','utf8');assert(source.includes('odontologia:'));for(const file of ['public/admin-mobile.html','public/admin-prospeccao.html'])assert(fs.readFileSync(file,'utf8').includes('value="odontologia"'));});
