const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function storage(){const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)};}
function browser(fetchFn){const ls=storage(),ss=storage(),events={},redirects=[],w={location:{replace:x=>redirects.push(x),href:''},addEventListener:(type,fn)=>events[type]=fn};const ctx=vm.createContext({localStorage:ls,sessionStorage:ss,window:w,document:{addEventListener:()=>{}},navigator:{},API_BASE:'https://app.fixture/api',fetch:fetchFn,atob:x=>Buffer.from(x,'base64').toString(),console,Date,Error,JSON});vm.runInContext(fs.readFileSync('patches/assets/auth-persistente.js','utf8')+'\n'+fs.readFileSync('patches/assets/api-persistente.js','utf8'),ctx);return{ctx,ls,ss,events,redirects,call:code=>vm.runInContext(code,ctx)};}
const expires=()=>Math.floor(Date.now()/1000)+3600;const response=(status,body)=>({status,ok:status>=200&&status<300,json:async()=>body,text:async()=>JSON.stringify(body)});
function seed(x,refresh='refresh-fixture-1',expire=1){x.ls.setItem('lojaia_sessao',JSON.stringify({usuario:{id:'owner'},token:'expired-token',refresh_token:refresh,expires_at:expire}));x.ss.setItem('lojaia_loja_atual',JSON.stringify({id:'shop'}));}
test('login lembrado salva renovação sem armazenar senha; sessão temporária continua temporária',()=>{const x=browser();x.call("salvarSessao({id:'owner'},'access',true,'refresh-fixture',123)");const s=JSON.parse(x.ls.getItem('lojaia_sessao'));assert.equal(s.refresh_token,'refresh-fixture');assert(!('senha'in s));x.call("salvarSessao({id:'owner'},'access',false,'refresh-temp',123)");assert.equal(x.ls.getItem('lojaia_sessao'),null);assert(x.ss.getItem('lojaia_sessao'));});
test('várias APIs simultâneas renovam uma vez e preservam loja selecionada',async()=>{let refreshes=0,apiTokens=[];const x=browser(async(url,opts)=>{if(url.endsWith('/refresh')){refreshes++;await new Promise(r=>setTimeout(r,20));return response(200,{usuario:{id:'owner'},token:'new-access',refresh_token:'new-refresh',expires_at:expires()});}apiTokens.push(opts.headers.Authorization);return response(200,{ok:true});});seed(x);await x.call("Promise.all([apiFetch('/lojas'),apiFetch('/lojas/shop/marca'),apiFetch('/lojas/shop/galeria')])");assert.equal(refreshes,1);assert(apiTokens.every(t=>t==='Bearer new-access'));assert(x.ss.getItem('lojaia_loja_atual'));assert.equal(JSON.parse(x.ls.getItem('lojaia_sessao')).refresh_token,'new-refresh');});
test('offline, 503 e 429 mantêm a sessão, sem redirecionar ou perder formulário',async()=>{for(const status of [0,503,429]){const x=browser(async()=>{if(!status)throw Error('offline');return response(status,{erro:'tente novamente'});});seed(x);await assert.rejects(()=>x.call("apiFetch('/lojas')"));assert(x.ls.getItem('lojaia_sessao'));assert(x.ss.getItem('lojaia_loja_atual'));assert.equal(x.redirects.length,0);}});
test('refresh revogado encerra sessão, mas erro de senha não limpa sessão existente',async()=>{const x=browser(async()=>response(401,{erro:'revogado'}));seed(x);await assert.rejects(()=>x.call("apiFetch('/lojas')"));assert.equal(x.ls.getItem('lojaia_sessao'),null);assert.equal(x.redirects[0],'login.html');const y=browser(async()=>response(401,{erro:'senha incorreta'}));seed(y);await assert.rejects(()=>y.call("apiFetch('/auth/login',{method:'POST',body:'{}'})"));assert(y.ls.getItem('lojaia_sessao'));assert.equal(y.redirects.length,0);});
test('401 renova e repete uma vez; gravação não é enviada antes de token válido',async()=>{let r=0,a=0;const x=browser(async(url,opts)=>{if(url.endsWith('/refresh')){r++;return response(200,{usuario:{id:'owner'},token:'fresh',refresh_token:'rotated',expires_at:expires()});}a++;return response(a===1?401:200,{ok:true});});seed(x,'refresh-fixture',expires());await x.call("apiFetch('/lojas/shop/galeria',{method:'POST',body:'{\"descricao\":\"Foto\"}'})");assert.equal(r,1);assert.equal(a,2);assert.equal(x.redirects.length,0);});
test('logout ou troca de usuário durante refresh não ressuscita a conta antiga',async()=>{let resolve;const x=browser(()=>new Promise(r=>resolve=r));seed(x);const p=x.call('renovarSessao()');x.call('limparSessao()');resolve(response(200,{usuario:{id:'owner'},token:'fresh',refresh_token:'rotated',expires_at:expires()}));await p;assert.equal(x.ls.getItem('lojaia_sessao'),null);});
test('renovação em outra aba não redireciona; logout ou troca de conta redireciona',()=>{const x=browser();x.events.storage({key:'lojaia_sessao',oldValue:JSON.stringify({usuario:{id:'owner'},token:'old'}),newValue:JSON.stringify({usuario:{id:'owner'},token:'new'})});assert.equal(x.redirects.length,0);x.events.storage({key:'lojaia_sessao',oldValue:JSON.stringify({usuario:{id:'owner'}}),newValue:null});assert.equal(x.ctx.window.location.href,'login.html');});
function controller(factory){const m={exports:{}};vm.runInNewContext(fs.readFileSync('patches/assets/authSessao.controller.js','utf8'),{module:m,process:{env:{SUPABASE_URL:'https://fixture.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'private'}},require:p=>({createClient:factory})});return m.exports;}
function res(){return{statusCode:200,headers:{},set(k,v){this.headers[k]=v;return this},status(code){this.statusCode=code;return this},json(body){this.body=body;return this}};}
test('servidor troca refresh em cliente isolado, sem expor chave nem guardar sessão global',async()=>{let factories=0;const c=controller((url,key,opts)=>{factories++;assert.equal(opts.auth.persistSession,false);return{auth:{refreshSession:async({refresh_token})=>({data:{user:{id:'owner'},session:{access_token:'access',refresh_token:'rotated',expires_at:123}}})}};});for(let i=0;i<2;i++){const r=res();await c.renovar({body:{refresh_token:'refresh-fixture'}},r);assert.equal(r.statusCode,200);assert.equal(r.body.refresh_token,'rotated');assert.equal(r.headers['Cache-Control'],'no-store');assert(!JSON.stringify(r.body).includes('private'));}assert.equal(factories,2);});
test('servidor diferencia refresh inválido e falha temporária; logout revoga somente sessão local',async()=>{for(const status of [400,401,500,0]){const c=controller(()=>({auth:{refreshSession:async()=>({error:{status}})}}));const r=res();await c.renovar({body:{refresh_token:'refresh-fixture'}},r);assert.equal(r.statusCode,status===400||status===401?401:503);}let scope;const c=controller(()=>({auth:{admin:{signOut:async(token,s)=>{scope=s;return{}}}}}));await c.sair({headers:{authorization:'Bearer access'}},res());assert.equal(scope,'local');});
test('Android exige confirmação para ativar/desativar, bloqueia pausa e permite prints no Cliente',()=>{for(const pkg of ['stock','admin']){const module=pkg==='stock'?'estoqueapp':'adminapp';const s=fs.readFileSync('android-app/'+module+'/src/main/java/com/saintsai/'+pkg+'/SaintsSecurity.java','utf8');assert.match(s,/requestSecurityToggle.*authenticate/);assert.match(s,/if\(enabled\(\)\)lock\(\)/);if(pkg==='stock')assert.doesNotMatch(s,/FLAG_SECURE/);else assert.match(s,/FLAG_SECURE/);assert.match(s,/BIOMETRIC_STRONG/);assert.match(s,/DEVICE_CREDENTIAL/);assert.match(s,/RESULT_OK/);assert.match(s,/toggleTarget!=null.*prefs.edit/s);assert.match(s,/if\(active\)success\(\)/);}});
