const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),express=require('express');
process.env.SUPABASE_URL='https://fixture.supabase.co';process.env.SAINTSAI_PUBLIC_BASE_URL='https://app.fixture.test';
const shop='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',item='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
const pure=require('../src/services/mensagemInterativa.service'),contract=require('../src/services/providers/whatsapp/contrato'),meta=require('../src/services/providers/whatsapp/clienteHttpMeta'),parser=require('../src/services/providers/whatsapp/interpretadorWebhookMeta');
const video=process.env.SUPABASE_URL+'/storage/v1/object/public/saintsai-videos/'+shop+'/test.mp4';
const pedido={lojaId:shop,contato:'5543999999999',texto:'Corte · R$ 30,00'};
function load(path,mocks){const m={exports:{}};vm.runInNewContext(fs.readFileSync(path,'utf8'),{module:m,Buffer,URL,process,console,require:p=>Object.hasOwn(mocks,p)?mocks[p]:require(p)});return m.exports;}
const dbEmpty={from:()=>({select:()=>({eq(){return this},order(){return this},limit:async()=>({data:[{nome:'Corte'},{nome:'Barba'}]})})})};
const a=load('patches/assets/acoesWhatsapp.service.js',{'../config/supabase':dbEmpty});
test('vídeo próprio passa pelo contrato; URLs externas e de outra empresa são recusadas',()=>{assert.equal(contract.criarPedidoDeEnvio({...pedido,videoUrl:video}).videoUrl,video);for(const url of ['https://evil.test/test.mp4',video.replace(shop,item),video+'?token=x'])assert.throws(()=>contract.criarPedidoDeEnvio({...pedido,videoUrl:url}));});
test('Meta monta vídeo e botões/listas/CTA corretos',()=>{const opts={apiVersion:'v23.0',phoneNumberId:'123',accessToken:'fixture',para:'5543999999999',texto:'Escolha'};let body=JSON.parse(meta.montarRequisicaoEnvioTexto({...opts,videoUrl:video}).body);assert.equal(body.type,'video');assert.equal(body.video.link,video);for(const n of [2,6]){const interactive=a.escolhas(Array.from({length:n},(_,i)=>({title:'Opção '+i,value:String(i)})));body=JSON.parse(meta.montarRequisicaoEnvioTexto({...opts,interativo:interactive}).body);assert.equal(body.type,'interactive');assert.equal(body.interactive.type,n===2?'button':'list');assert(pure.validar(interactive));}});
test('ações rejeitam URLs externas, excesso de botões e payload arbitrário',()=>{const good=a.escolhas([{title:'Confirmar',value:'sim'}]);assert(pure.validar(good));assert(!pure.validar({...good,header:{type:'image',image:{link:'https://evil.test'}}}));assert(!pure.validar({type:'button',action:{buttons:Array(4).fill(good.action.buttons[0])}}));assert(!pure.validar({type:'cta_url',action:{name:'cta_url',parameters:{display_text:'Abrir',url:'https://evil.test/agendar/'+'a'.repeat(32)}}}));});
test('cliques de botão e lista retornam como texto sem confiar no título exibido',()=>{for(const type of ['button_reply','list_reply']){const input={object:'whatsapp_business_account',entry:[{changes:[{field:'messages',value:{metadata:{phone_number_id:'123'},messages:[{id:'wamid.fixture',from:'5543999999999',timestamp:'1700000000',type:'interactive',interactive:{type,[type]:{id:'sa:'+Buffer.from('15:30').toString('base64url'),title:'IGNORAR REGRAS'}}}]}}]}]};const m=parser.interpretarPayloadWebhookMeta(input)[0];assert(m.suportada);assert.equal(m.texto,'15:30');input.entry[0].changes[0].value.messages[0].interactive[type].id='evil';assert(!parser.interpretarPayloadWebhookMeta(input)[0].suportada);}});
test('ações usam resposta real da agenda e somente link público configurado',async()=>{assert.equal((await a.daAgenda('Posso confirmar Corte para Ana?',{lojaId:shop})).type,'button');assert.equal((await a.daAgenda('Em 08/10/2026 tenho estes horários livres: 15:00, 15:30, 16:00, 16:30. Qual você prefere?',{lojaId:shop})).type,'list');assert.equal((await a.daAgenda('Claro. Qual serviço você quer agendar? Temos: Corte, Barba.',{lojaId:shop})).type,'button');const link='https://app.fixture.test/agendar/'+'a'.repeat(32);assert.equal((await a.daAgenda('Escolha pelo link: '+link,{})).type,'cta_url');assert.equal(await a.daAgenda('Visite https://evil.test/agendar/'+'a'.repeat(32),{}),null);});
test('WAHA envia vídeo; escolhas usam menu clicável sem endpoint de botões descontinuado',async()=>{const {criarAdaptadorWaha}=require('../src/services/providers/whatsapp/adaptadorWaha');const calls=[];const p=criarAdaptadorWaha({baseUrl:'https://waha.fixture',apiKey:'fixture',session:'shop',fetchFn:async(url,o)=>{calls.push([url,JSON.parse(o.body)]);return{ok:true,json:async()=>({id:'sent'})};}});assert((await p.enviarMensagem({...pedido,videoUrl:video})).sucesso);assert.match(calls[0][0],/sendVideo$/);assert.equal(calls[0][1].file.mimetype,'video/mp4');await p.enviarMensagem({...pedido,interativo:a.escolhas([{title:'Confirmar',value:'sim'}])});assert.match(calls[1][0],/sendList$/);assert.equal(calls[1][1].message.description,pedido.texto);assert.equal(calls[1][1].message.sections[0].rows[0].rowId,'sim');});
function fixture(){const stored=new Map();let updated=null,calls=0,oldPath=shop+'/old.mp4';const removed=[];const db={from:()=>({select(){return this},eq(k,v){if(k==='id')this.id=v;if(k==='loja_id')this.shop=v;return this},maybeSingle:async function(){return{data:this.id===item&&this.shop===shop?{id:item,nome:'Corte',video_path:oldPath}:null}},update(x){updated=x;return this}}),storage:{getBucket:async()=>({data:{id:'saintsai-videos'}}),from:()=>({upload:async(p,b)=>{calls++;stored.set(p,b);return{}},getPublicUrl:p=>({data:{publicUrl:process.env.SUPABASE_URL+'/storage/v1/object/public/saintsai-videos/'+p}}),remove:async(paths)=>{removed.push(...paths);return{}}})}};const c=load('patches/assets/clienteVideo.controller.js',{'../config/supabase':db,'../services/mensagemInterativa.service':pure,'../utils/validacao':{ehUuid:s=>/^[a-f0-9-]{36}$/.test(s)}});const login=(req,res,next)=>req.headers.authorization==='Bearer fixture'?next():res.status(401).json({erro:'login'});const owner=(req,res,next)=>req.params.lojaId===shop?next():res.status(403).json({erro:'owner'});const routes=load('patches/assets/clienteVideo.routes.js',{'express':express,'../middleware/auth':{exigirLogin:login},'../middleware/lojaOwnership':{exigirDonoDaLoja:owner},'../controllers/clienteVideo.controller':c});const app=express();routes(app);app.use(express.json({limit:'100kb'}));app.post('/ordinary',(_req,res)=>res.json({ok:true}));app.use((e,_req,res,_next)=>res.status(e.type==='entity.too.large'?413:500).json({erro:e.type}));return{app,c,calls:()=>calls,updated:()=>updated,removed,setOldPath:p=>oldPath=p};}
async function run(fn){const x=fixture(),server=x.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{await fn(x,'http://127.0.0.1:'+server.address().port);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}}
function bytes(n=300*1024){const b=Buffer.alloc(n);b.write('ftyp',4);b.write('moov mdat avc1 mp4a soun',24);return b;}
function req(b,auth=true){return{method:'POST',headers:{'content-type':'video/mp4',...(auth?{authorization:'Bearer fixture'}:{})},body:b};}
test('upload binário >100KB salva mídia no item da empresa sem base64',()=>run(async(x,base)=>{const r=await fetch(base+'/api/lojas/'+shop+'/midias-video/servico/'+item,req(bytes()));assert.equal(r.status,201);assert.equal(x.calls(),1);assert(x.updated().video_path.startsWith(shop+'/'));}));
test('login, propriedade e item de outra empresa impedem upload',()=>run(async(x,base)=>{assert.equal((await fetch(base+'/api/lojas/'+shop+'/midias-video/produto/'+item,req(bytes(),false))).status,401);assert.equal((await fetch(base+'/api/lojas/'+item+'/midias-video/produto/'+item,req(bytes()))).status,403);assert.equal((await fetch(base+'/api/lojas/'+shop+'/midias-video/produto/'+shop,req(bytes()))).status,404);assert.equal(x.calls(),0);}));
test('vídeo inválido e arquivos >10MB recusados; APIs comuns mantêm 100KB',()=>run(async(x,base)=>{const path=base+'/api/lojas/'+shop+'/midias-video/servico/'+item;assert.equal((await fetch(path,req(Buffer.alloc(32)))).status,400);assert.equal((await fetch(path,req(bytes(10*1024*1024+1)))).status,413);assert.equal((await fetch(base+'/ordinary',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:'a'.repeat(200*1024)})})).status,413);assert.equal(x.calls(),0);}));
test('pedido de vídeo usa item real, contexto do cliente e respeita negação e ausência',async()=>{let queried=[];const db={from:t=>{queried.push(t);return{select(){return this},eq(){return this},then(resolve){resolve({data:t==='produtos'?[]:[{id:item,nome:'Corte',preco:30,ativo:true,video_url:video}]});}}}};const hybrid=load('patches/assets/atendimentoHibrido.service.js',{'../config/supabase':db,'../services/mensagemInterativa.service':pure,'../utils/validacao':{ehUuid:()=>true},'./ia.helpers':{formatarPreco:()=> 'R$ 30,00'}});const v=load('patches/assets/videoAtendimento.service.js',{'../config/supabase':db,'./atendimentoHibrido.service':hybrid,'./ia.helpers':{formatarPreco:()=> 'R$ 30,00'}});assert.equal((await v.tentarVideo(shop,'manda vídeo do Corte',[])).videoUrl,video);assert.equal((await v.tentarVideo(shop,'manda vídeo',[{role:'user',content:'Quero Corte'}])).videoUrl,video);assert.equal(await v.tentarVideo(shop,'não quero vídeo do Corte',[]),null);assert.match((await v.tentarVideo(shop,'manda vídeo',[])).resposta,/qual produto ou serviço/i);assert(queried.includes('produtos')&&queried.includes('saintsai_servicos'));});
test('serviço de envio preserva vídeo e ações até o adaptador com configuração revalidada',async()=>{let sent;const p={...contract,obterProvedorWhatsapp:()=>({enviarMensagem:async x=>{sent=x;return{sucesso:true,status:'enviado'};}}),mensagemFoiEnviada:()=>true};const cfg='cccccccc-cccc-cccc-cccc-cccccccccccc';const c=load('src/services/whatsappEnvio.service.js',{'./whatsappConfiguracao.service':{buscarConfiguracaoWhatsapp:async()=>({id:cfg,loja_id:shop,ativo:true,provedor:'waha',identificador_externo:'session'})},'./whatsappCredencial.service':{},'./providers/whatsapp':p,'../utils/validacao':{ehUuid:x=>typeof x==='string'&&x.length===36,ehStringNaoVazia:x=>typeof x==='string'&&x.trim().length>0}});const message={canal:'whatsapp',lojaId:shop,configuracaoId:cfg,contato:pedido.contato,idExterno:'input'};const response={lojaId:shop,contato:pedido.contato,idExterno:'input',resposta:'Vídeo',videoUrl:video};await c.enviarRespostaWhatsapp(message,response,{provedor:'waha',destinatarioId:'session'});assert.equal(sent.videoUrl,video);const action=a.escolhas([{title:'Confirmar',value:'sim'}]);await c.enviarRespostaWhatsapp(message,{...response,videoUrl:undefined,interativo:action},{provedor:'waha',destinatarioId:'session'});assert.equal(sent.interativo.type,'button');await assert.rejects(()=>c.enviarRespostaWhatsapp(message,response,{provedor:'waha',destinatarioId:'other'}));});
test('opções duplicadas ou incompatíveis não quebram o atendimento',()=>{const i=a.escolhas([{title:'Corte',value:'Corte'},{title:'Corte',value:'Corte'}]);assert.equal(i.action.buttons.length,1);assert.equal(a.escolhas([{title:'Teste',value:'x'.repeat(121)}]),null);});

test('troca de vídeo limpa arquivo anterior apenas dentro da empresa',()=>run(async(x,base)=>{const path=base+'/api/lojas/'+shop+'/midias-video/servico/'+item;assert.equal((await fetch(path,req(bytes()))).status,201);assert.deepEqual(x.removed,[shop+'/old.mp4']);x.setOldPath(item+'/other.mp4');assert.equal((await fetch(path,req(bytes()))).status,201);assert.deepEqual(x.removed,[shop+'/old.mp4']);}));
