const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function harness({cfg={id:'cfg',provedor:'waha',ativo:true},status={status:'WORKING',connected:true,verified:true,numero:'5544991001088'},offline=false,conflict=false}={}){let writes=[],statusCalls=0;const db={from(){let payload,filters={};const q={select(){return q},eq(k,v){filters[k]=v;return q},order(){return q},limit(){return q},update(v){payload=v;return q},insert(v){payload=v;return q},single:async()=>result(true),then(resolve,reject){return Promise.resolve(result(false)).then(resolve,reject)}};function result(single){if(payload){writes.push({payload,filters});return{data:{id:'new',provedor:'waha',...payload},error:conflict?{code:'23505'}:null}}return{data:cfg?[cfg]:[],error:null}}return q}};const src=fs.readFileSync('src/controllers/clienteHub.controller.js','utf8');const start=src.indexOf('async function statusWhatsappCliente('),end=src.indexOf('async function parearWhatsappCliente(',start);const module={exports:{}};vm.runInNewContext(src.slice(start,end)+'\nmodule.exports=statusWhatsappCliente;',{module,supabase:db,wahaOnboarding:{status:async()=>{statusCalls++;if(offline)throw Error();return status},sessionName:()=> 'session'},exigirLoja:async()=>({id:'own'}),console:{error(){}},Date,String,Boolean});return{writes,get statusCalls(){return statusCalls},async run(){const res={statusCode:200,status(n){this.statusCode=n;return this},json(x){this.body=x;return this}};await module.exports({},res);return res}}}
test('conexão verificada sincroniza número real apenas na loja selecionada',async()=>{const h=harness();const r=await h.run();assert.equal(r.body.conectado,true);assert(h.writes.every(w=>w.filters.loja_id==='own'));assert.equal(h.writes[0].payload.numero_whatsapp,'5544991001088')});
test('Meta teste não impede reconhecer QR e não é sobrescrito como provedor Waha',async()=>{const h=harness({cfg:{id:'meta',provedor:'meta',numero_whatsapp:'15551963387',ativo:true}});const r=await h.run();assert.equal(r.body.provedor,'waha');assert.equal(h.writes[0].payload.provedor,'waha');assert.equal(h.writes[0].payload.loja_id,'own')});
test('Meta teste sem QR não é mostrado como WhatsApp real conectado',async()=>{const h=harness({cfg:{id:'meta',provedor:'meta',numero_whatsapp:'15551963387',ativo:true},status:{status:'NOT_FOUND',connected:false}});assert.equal((await h.run()).body.conectado,false);assert.equal(h.writes.length,0)});
test('Meta real continua funcionando sem depender do servidor de QR',async()=>{const h=harness({cfg:{provedor:'meta',numero_whatsapp:'5544991001088',ativo:true},offline:true});assert.equal((await h.run()).body.conectado,true);assert.equal(h.statusCalls,0)});
test('falha temporária preserva configuração ativa e retorna 503',async()=>{const h=harness({offline:true});assert.equal((await h.run()).statusCode,503);assert.equal(h.writes.length,0)});
test('WORKING sem identidade permanece pendente sem desativar registro',async()=>{const h=harness({status:{status:'WORKING',connected:false,verified:false}});const r=await h.run();assert.match(r.body.mensagem,/confirmando/);assert.equal(h.writes.length,0)});
test('sessão comprovadamente parada desativa apenas vínculo da loja atual',async()=>{const h=harness({status:{status:'STOPPED',connected:false}});assert.equal((await h.run()).body.conectado,false);assert.equal(h.writes[0].payload.ativo,false);assert.equal(h.writes[0].filters.loja_id,'own')});
test('tela consulta ao retornar e recarrega seleção da conta',()=>{const p=fs.readFileSync('public/cliente-whatsapp.html','utf8');assert.match(p,/visibilitychange/);assert.match(p,/setInterval/);assert.match(p,/forcarRecarregar:true/);assert.match(p,/verificando=true/)});

test('número vinculado a outra loja informa conflito sem alterar o outro vínculo',async()=>{const h=harness({conflict:true});const r=await h.run();assert.equal(r.statusCode,409);assert.match(r.body.erro,/outra loja/);assert.equal(h.writes.length,1);assert.equal(h.writes[0].filters.loja_id,'own')});
