plugins {
    id 'com.android.application'
}

android {
    namespace 'com.saintsai.sales'
    compileSdk 35

    defaultConfig {
        applicationId "com.saintsai.sales"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:33.7.0')
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'androidx.core:core:1.15.0'
}
